### ISSUE TITLE
USE_VTK on debian 

### ISSUE THREAD

**Issue by eolivi** [openmeeg/openmeeg#114]
Hello,

I made a few tries, and it looks like :
-vtk support does not work on debiar with vtk5.

-It works with vtk6. if you force the option USE_VTK to True at OpenMEEG level.
I don't understand why but the parent opiton USE_VTK (declared in cmake/Options.cmake) does not give its value to the subproject OpenMEEG. ( but it works well for other options as USE_OMP)...
so, even specifying USE_VTK at project level, it will not compile the tools that are using vtk.

BTW in VtkOptions.cmake: why do we have such components ?
    find_package(VTK COMPONENTS vtkIOXML vtkIOLegacy vtkRenderingOpenGL vtkInteractionStyle NO_MODULE)
We need only vtkIOXML and Legacy, no ?

**Comment by agramfort** [comment]
no idea. @papadop is behind this :)

**Comment by eolivi** [comment]
ok !!! I've finally found.
in this file: cmake/externals/projects_modules/OpenMEEG.cmake
I have to add
         -DUSE_VTK:BOOL=${USE_VTK}
goood !!

**Comment by agramfort** [comment]
you need to edit the files to config this option???

**Comment by eolivi** [comment]
I think that in this file are the options that subprojects inherit.
If you don't specify it there, then making a new option at ground level will not propagate to subprojects.
(@papadop should confirm that...)

**Comment by agramfort** [comment]
it should be possible to use vtk from base cmakelist

**Comment by papadop** [comment]
Confirmed. You need to propagate options from the super-project to the downstream projects. The super-projects and all downstream projects are totally separate projects (in the cmake sense). So yes adding 
-DUSE_VTK:BOOL=${USE_VTK} is probably the proper thing to do (saying probably, because I havenot cheecked).

**Comment by eolivi** [comment]
ok I'll commit that soon.
Thank you ;-)

**Comment by eolivi** [comment]
and BTW, Theo @papadop 
in VtkOptions.cmake: why do we have such components ?
find_package(VTK COMPONENTS vtkIOXML vtkIOLegacy vtkRenderingOpenGL vtkInteractionStyle NO_MODULE)
We need only vtkIOXML and Legacy, no ?

**Comment by agramfort** [comment]
Reopening so @papadop can comment

**Comment by agramfort** [comment]
for the record @eolivi and gave a quick try to have travis use vtk but no success

https://travis-ci.org/openmeeg/openmeeg/builds/173494912

**Comment by eolivi** [comment]
can I submit and finally close this @papadop  @agramfort ?
https://github.com/eolivi/openmeeg/commit/34bb28a93cc6bb157613befffa66decac413f210

**Comment by agramfort** [comment]
go for it

**Comment by eolivi** [comment]
there it is
https://github.com/openmeeg/openmeeg/pull/147

**Comment by eolivi** [comment]
ok to close this time ?

**Comment by agramfort** [comment]
yes
