### ISSUE TITLE
OpenMEEG BEM stops in Brainstorm3

### ISSUE THREAD

**Issue by CNatatani** [openmeeg/openmeeg#118]
Dear OpenMEEG developer,

I use OpneMEEG with Brainstorm3 Jun-02-2016/MATLAB Runtime Compiler 2015b on Win7 PC (memory: 12GB, virtual memory:40GB) to generating a forward model with BEM for EEG data.  

BEM layers were created from Freesurfer anatomical data, and each layers have 1922 vertices. Source space was limited to cortex surface.

Brainstorm3 has Open MEEG options menu.  when I choose 'Use adjoint formulation', I can create  a model.  However, when I choose 'Use adaptive integration' option (estimated resources were, memory: 690Mb and hard drive: 1379Mb), I get following error message:

---

*\* Error: OpenMEEG call: om_minverser
*\*       "C:\Users\u1.brainstorm\tmp\openmeeg_hm.mat"
*\*       "C:\Users\u1\Documents\brainstorm_db\BS_prtcl1\anat\Subject01
\tess_innerskull_bem_1922V_openmeeg.mat"
*\* OpenMEEG error #-1073741819:
*\* om_minverser version 2.2.0 (exported) compiled at Feb 19 2013 13:59:57
**
*\* | ------ om_minverser
*\* | C:\Users\u0080389.brainstorm\tmp\openmeeg_hm.mat
*\* | C:\Users\u0080389\Documents\brainstorm_db\BS_prtcl1\anat\Subject01\tess
_innerskull_bem_1922V_openmeeg.mat
*\* | -----------------------
**
*\* Many OpenMEEG crashes are due to a lack of memory.
*\* Reduce the number of vertices on each BEM layer and try again.

---

I got the same error when I tried to run the process in a VM with Windows Server 2012 with dynamic memory allocation. Minimal setup are 24 GB RAM and a virtual memory on the virtual hard drive of  100GB.   It does not look like a memory error.   I would appreciate if you you know how to avoid the crush.

Best,

CNakatani

**Comment by agramfort** [comment]
if adjoint works and not the other I suggest a problem of memory or disk
usage with temporary files.

are you using a 64bits windows?

**Comment by CNatatani** [comment]
Yes. I'm using 64bits windows.  I tried with Win7 PC (memory: 12GB, virtual memory:40GB), and with Windows Server 2012 (dynamic memory allocation. Minimal setup are 24 GB RAM and a virtual memory on the virtual hard drive of 100GB). In both cases, I experienced the same error.

**Comment by CNatatani** [comment]
Yes and no.  In 2016, we could not solve the problem on the Windows server. Therefore, we moved to a Ubuntu machine with a Matlab license.  Since then, I did not experience the problem. I believe the total memory size of the Ubuntu machine is 16GB or so.   It has a better graphic card than the windows server, but I'm not sure if it matters.
