### ISSUE TITLE
Build fails on OSX 10.10

### ISSUE THREAD

**Issue by dpo** [openmeeg/openmeeg#139]
On OSX, the Accelerate framework provides the necessary BLAS and LAPACK implementation, including `cblas.h` and `clapack.h`. It seems `openmeeg` only looks for ATLAS or MKL. I have to set `-DUSE_ATLAS=OFF` and `-DCMAKE_C_FLAGS=-framework Accelerate` to get CMake to find `cblas.h` and `clapack.h`. However, I then hit the build error:

```
/tmp/openmeeg-20161015-82762-q9osu7/openmeeg-release-2.1/libs/MatLib/MatLib/MatLibConfig.h:54:18: fatal error: 'FC.h' file not found
        #include <FC.h>
                 ^
```

**Comment by agramfort** [comment]
code should work on mac. Travis is normally testing it. See:

https://github.com/openmeeg/openmeeg/blob/master/.travis.yml
https://github.com/openmeeg/openmeeg/blob/master/build_tools/travis/before_install.sh
https://github.com/openmeeg/openmeeg/blob/master/build_tools/travis/install.sh

does it help? 

basically we install stuff with homebrew
then running a long cmake command with necessary options.

does it help?

**Comment by ilovezfs** [comment]
@agramfort when building for macOS, your Travis configuration appears to use OpenBLAS. @dpo above is talking about using the Accelerate framework, which ships natively with macOS.

**Comment by agramfort** [comment]
@dpo can you paste the full line you use with cmake

cmake -DCMAKE_C_FLAGS=-framework Accelerate ...

?

I can then try on my mac.

**Comment by ilovezfs** [comment]
@agramfort basically anything depending on `veclibfort` should be a useful example for you by the way
https://gist.github.com/ilovezfs/3977538f7c847b6c8f99d8686262c07b

**Comment by dpo** [comment]
@agramfort Sorry for the delay. Here's my complete CMake command:
```
cmake . -DUSE_PROGRESSBAR=ON -DUSE_ATLAS=OFF -DCMAKE_C_FLAGS=-framework Accelerate -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/openmeeg/2.1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
```
(the space between `-framework` and `Accelerate` is escaped in Homebrew; you'll probably have to add quotes.)

**Comment by agramfort** [comment]
this worked on my machine but I may have this FC.h somewhere on my system.

this FC.h is produced by this macro:

https://github.com/openmeeg/openmeeg/blob/master/OpenMEEG/cmake/FortranCInterface.cmake

not sure how to help you debug this ...

**Comment by dpo** [comment]
Is there any chance you could move your `FC.h` out of the way and let me know if the macro generates it for you? It doesn't do it for me.

**Comment by papadop** [comment]
Normally, if everything goes well the FC.h should appear in your build directory. If you started for a clean build dir, and you found it, it means that it has been generated. If it is not generated in your build directory, something is wrong...

**Comment by agramfort** [comment]
I can confirm that with this build config the FC.h file is not produced... this is bad :( 

mine contains :

```
#ifndef FC_HEADER_INCLUDED
#define FC_HEADER_INCLUDED

/* Mangling for Fortran global symbols without underscores. */
#define FC_GLOBAL(name,NAME) NAME##_

#endif
```

this needs to be fixed...

**Comment by agramfort** [comment]
actually pb comes from here:

https://github.com/openmeeg/openmeeg/blob/master/OpenMEEG/cmake/UseAtlas.cmake#L43

we considered that USE_ATLAS on macos means use vecLib which is now called accelerate?

if you change these lines to:

        set(LAPACK_LIBRARIES "-framework Accelerate")
        include_directories(/System/Library/Frameworks/Accelerate.framework/Headers)

and set USE_ATLAS to True does it work?

**Comment by dpo** [comment]
No luck. I realize I didn't mention in my original post that I'm building the release, not `master` (in Homebrew/Science, we tend to avoid head-only formulae). I tried patching as follows
```diff
diff --git a/macros/UseAtlas.cmake b/macros/UseAtlas.cmake
index 158890c..0e12eb9 100644
--- a/macros/UseAtlas.cmake
+++ b/macros/UseAtlas.cmake
@@ -165,8 +165,8 @@ IF (NOT USE_MKL)
         ENDIF()
     ELSE() # Assume APPLE or local lapack/blas (treated in contrib)
         IF (APPLE)
-            SET(LAPACK_LIBRARIES "-framework vecLib")
-            INCLUDE_DIRECTORIES(/System/Library/Frameworks/vecLib.framework/Headers)
+            SET(LAPACK_LIBRARIES "-framework Accelerate")
+            INCLUDE_DIRECTORIES(/System/Library/Frameworks/Accelerate.framework/Headers)
         ENDIF()
     ENDIF()
 ENDIF()
```
I call CMake with
```
cmake . -DUSE_ATLAS=ON -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/openmeeg/2.1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
```
and I obtain
```
...
-- checking Fortran function linkage: DAXPY_
-- Looking for DAXPY_ in /usr/lib/libblas.dylib
-- Looking for DAXPY_ in /usr/lib/libblas.dylib - found
-- found Fortran function linkage
-- Detecting Fortran/C Interface - Failed to recognize symbols
...
```
and the build fails because `cblas.h` is not found. On my system, that file is in
```
/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers/cblas.h
```
I'm not CMake-literate but couldn't we use [`Findveclib.cmake`](https://github.com/BVLC/caffe/blob/master/cmake/Modules/FindvecLib.cmake) or something like that here?

If I try to build `master`, I get
```
-- verifying file...
       file='/tmp/openmeeg-20161028-18100-8lpmkc/zlib/zlib-1.2.8.tar.gz'
-- Downloading... done
/usr/local/Cellar/cmake/3.6.2/bin/cmake -P /tmp/openmeeg-20161028-18100-8lpmkc/zlib/stamp/verify-zlib.cmake
/usr/local/Cellar/cmake/3.6.2/bin/cmake -P /tmp/openmeeg-20161028-18100-8lpmkc/zlib/stamp/extract-zlib.cmake
-- extracting...
     src='/tmp/openmeeg-20161028-18100-8lpmkc/zlib/zlib-1.2.8.tar.gz'
     dst='/tmp/openmeeg-20161028-18100-8lpmkc/zlib'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
/usr/local/Cellar/cmake/3.6.2/bin/cmake -E touch /tmp/openmeeg-20161028-18100-8lpmkc/zlib/stamp/zlib-download
```

**Comment by ilovezfs** [comment]
Maybe this would be worth git bisecting if someone knows the last time it worked.

**Comment by dpo** [comment]
It must have been before 2012 since the latest release is that old.

**Comment by agramfort** [comment]
did you try to build https://github.com/openmeeg/openmeeg/tree/release-2.2 ?

I've improved in master the detection of veclib

https://github.com/openmeeg/openmeeg/pull/140

thanks for the suggestion.

yeah the release is that old :( :(

**Comment by dpo** [comment]
@agramfort Thanks! The `release-2.2` branch fails just like the 2.1 release, but `master` patched with #140 builds! Phew! Two more points:

1. I got a build error if trying to build without DOxygen: https://gist.github.com/dpo/a13884b9c23f3ffcc315757d7261885b
2. I'm finding it a bit confusing that I have to say `USE_ATLAS` to mean "build with Accelerate"; those are two different implementations of the BLAS. It *is* possible to install ATLAS on OSX (though it's not easy), and that would be quite different from using Accelerate. You might want to make a separate CMake option here.

**Comment by agramfort** [comment]
>
> @agramfort <https://github.com/agramfort> Thanks! The release-2.2 branch
> fails just like the 2.1 release, but master patched with #140
> <https://github.com/openmeeg/openmeeg/pull/140> builds! Phew!
>

excellent


> Two more points:
>
>    1. I got a build error if trying to build without DOxygen:
>    https://gist.github.com/dpo/a13884b9c23f3ffcc315757d7261885b
>    <https://gist.github.com/dpo/a13884b9c23f3ffcc315757d7261885b>
>
> just set -DBUILD_DOCUMENTATION=OFF

so Doxygen will not be requested. It should fix it.

>
>    1.
>    2. I'm finding it a bit confusing that I have to say USE_ATLAS to mean
>    "build with Accelerate"; those are two different implementations of the
>    BLAS. It *is* possible to install ATLAS on OSX (though it's not easy),
>    and that would be quite different from using Accelerate. You might want to
>    make a separate CMake option here.
>
> agreed. Let's try to find the time to fix this...

did you do a "make test" to check everything is ok?

**Comment by dpo** [comment]
Thanks; `-DBUILD_DOCUMENTATION=OFF` worked.

`make test` wasn't recognized; `make check` works but unfortunately:
```
5% tests passed, 500 tests failed out of 528
```
Here are the full logs: https://gist.github.com/anonymous/c12ffd2ffd498949abab75dcc3e81880

When we've sorted through all of that, it might be time for a new release?!

**Comment by dpo** [comment]
In addition, when I run the sample data set (found in the README) with `compute_leadfields.sh`, I obtain: https://gist.github.com/4754c4a29864a365a3a6345796faf8b7.
There are a number of deprecation warnings and some errors opening files in there.

Let me know if I'm doing anything wrong. Thanks.

**Comment by agramfort** [comment]
the correct path to the sample data is now at:

https://github.com/openmeeg/openmeeg_sample_data/archive/master.zip

the readme.rst should now be up to date.

i merged a PR with happy CIs including on mac os using or not packages from
brew. See:

https://github.com/openmeeg/openmeeg/pull/140

does it help?

**Comment by dpo** [comment]
Ok, success! Many thanks for your help. It took a while to notice the difference between the two builds. In Homebrew, `libmatio` installs MATio, but `--enable-mat73` isn't on by default. I wonder why you have your own clones of MATio and HDF5. Are there any differences with the "official" distributions? In your scripts, you could `brew install libmatio --with-hdf5`.

A couple follow-up questions:
1. When do you think you could ship a new release? At Homebrew, we rather insist of building releases, not HEAD.
2. Is there a very small test that I could run on sample data and that would just take a few seconds? The sample data set takes a very long time and is too intensive for a quick test.

**Comment by agramfort** [comment]
thanks that helped

see my PR: https://github.com/openmeeg/openmeeg/pull/141

I have now a travis build on mac using libmatio from brew

before making a release I still have to fix this eisenbug in our linear algebra code. The errors appears also all the time on travis but only on mac os :(

to replicate:

```
for i in {1..9}; do ./libs/OpenMEEGMaths/tests/OpenMEEGMathsTest-full ; done | grep WRONG
```

you'll see that you have a random bug. The test fails about 1/3 of the times :(

**Comment by agramfort** [comment]
regarding using the sample data for testing you can just use our test suite with:

```
ctest .
```

or doing a `make check` as you did.

clear?

**Comment by agramfort** [comment]
random failure is related to 

https://github.com/openmeeg/openmeeg/pull/127

no success so far to fix this.

**Comment by ilovezfs** [comment]
any update here?

**Comment by agramfort** [comment]
nope. Did not find the bug yet... :(

any valgrind guru with blas / lapack apple expertise welcome...

**Comment by agramfort** [comment]
this is now fixed.
