### ISSUE TITLE
Can web('...') statement in FieldTrip's openmeeg Matlab code be removed, please?

### ISSUE THREAD

**Issue by nno** [openmeeg/openmeeg#145]
Greetings,

Currently FieldTrip's openmeeg Matlab code contains a function ``om_checkombin`` [1] that opens a webbrowser when called (using ``web('...')`` at line 13). I find this quite intrusive and annoying when running analyses or tests. In a discussion on the FieldTrip mailinglist [2], also @robertoostenveld, the project lead of FieldTrip, wrote about this: "I would personally not mind if it were to go, as I also find it annoying.". He suggested to contact you to discuss this issue.

Would you be open to the idea to remove the ``web(...)`` line?

Thank you for your consideration,
best,
Nick

[1] https://github.com/fieldtrip/fieldtrip/blob/master/external/openmeeg/om_checkombin.m
[2] http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3240

**Comment by agramfort** [comment]
See https://github.com/fieldtrip/fieldtrip/pull/316

let me know if it's ok for you.

cc @eolivi

**Comment by nno** [comment]
Looks great, thanks a lot. Much appreciated!

**Comment by robertoostenveld** [comment]
I have merged it into the fieldtrip release, thanks for the quick resolution. The issue here can be closed.

**Comment by nno** [comment]
Thanks @agramfort, @eolivi, @mclerc, @robertoostenveld. This is now resolved and I will close the issue.
