### ISSUE TITLE
Git tag for recent stable release

### ISSUE THREAD

**Issue by maedoc** [openmeeg/openmeeg#160]
Can we get a git tag on a recent but stable version of openmeeg?  Git master does not seem particularly stable or reliably buildable.

**Comment by eolivi** [comment]
Dear user,
As you have noticed, we are currently working on OpenMEEG, to make it more stable on all platforms and correct the issues.
We are planning a release very soon, until then, the master branch is more reliable than it was before (at least travis builds are now ok.).
Please tell us what are the issues you are having now on the master, or wait a few more weeks for a release.

**Comment by maedoc** [comment]
I'm building on Ubuntu 16 with `liblapack-dev libblas-dev liblapacke-dev` installed, so the cmake step runs fine, but running into errors such as 
```
../libs/OpenMEEG/src/libOpenMEEG.so.1.1.0: undefined reference to `clapack_dgetrf'
```
I'm just surprised as I thought the cmake step would've said something. 

I've now noticed that after `apt install libopenblas-dev` and specifying `BLASLAPACK_IMPLEMENTATION=OpenBLAS`, it seems to be working and all tests pass.

**Comment by maedoc** [comment]
I don't why I closed this. I still want a tag so that I can checkout a stable, recent version.  Even a beta, alpha or rc tag. The diff between release-2.1 and master is 3M lines long.

**Comment by agramfort** [comment]
@maedoc we're about to make a release. It should be imminent (I hope)

we'll make a release branch

**Comment by eolivi** [comment]
that is a prerelease but there it is:
https://github.com/openmeeg/openmeeg/tree/2.4.prerelease
;-)

**Comment by maedoc** [comment]
🍻 if ever the chance. thanks!
