### ISSUE TITLE
concerning the coding guidelines

### ISSUE THREAD

**Issue by eolivi** [openmeeg/openmeeg#164]
some propose KWStyle, and some uncrustify.

the issue is that the code is not uniformly indented or with brackets.

adjust coding guidelines or the project will split into LibreMEEG !

**Comment by papadop** [comment]
And as we have just seen KWStyle is just a checker, Beautifiers can also normalize the code.

**Comment by eolivi** [comment]
+1 for uncrustify as I 've just tested KWStyle and Uncrustify.

**Comment by agramfort** [comment]
if it works fine.

**Comment by larsoner** [comment]
Closing for #444
