### ISSUE TITLE
ECOG simulation

### ISSUE THREAD

**Issue by ftadel** [openmeeg/openmeeg#178]
See following thread on the Brainstorm forum:
http://neuroimage.usc.edu/forums/showthread.php?2832-sEEG-simulation-and-forward-model

**Comment by ftadel** [comment]
We have some more information to help debugging what is happening.
This user observe a crash I cannot reproduce on the same data, same OS and same Matlab version.
We are waiting for the openmeeg files that were generated at the moment of the crash.
http://neuroimage.usc.edu/forums/showthread.php?2832-sEEG-simulation-and-forward-model

Could it be that there is some missing library on the computer?
How could this be diagnosed? Can you list the exact list of libraries that must be installed on a Win10 home system in order to run OpenMEEG?

**Comment by eolivi** [comment]
I haven't seen any data yet. or do we have to used the one of fieldtrip ?
- OpenMEEG does not need any library to be installed on windows, they should be all included.
You could encourage her to try with the brand new packages that we have delivered there  http://openmeeg.gforge.inria.fr/download/?C=M;O=D:
[ ]	OpenMEEG-2.3.0.2-MacOSX-Intel-OpenBLAS-shared.tar.gz	2017-04-14 15:38 	12M	 
[ ]	OpenMEEG-2.3.0.2-Linux-OpenBLAS-shared.tar.gz	        2017-04-14 15:23 	11M	 
[ ]	OpenMEEG-2.3.0.2-Win64-OpenBLAS-python-shared.tar.gz	2017-04-14 11:26 	16M	 
[ ]	OpenMEEG-2.3.0.2-Win64-OpenBLAS-python-shared.exe	2017-04-14 11:26 	9.2M	 

it is not yet a new release but we would be glad to have some feedback.

**Comment by ftadel** [comment]
Rachel will post some data so you can try to understand what is going wrong.

It is a bit complicated to use other versions of OpenMEEG from Brainstorm, it's all integrated for people who don't really know how to install or compile anything on their computers... The files are downloaded automatically from the URLs listed here:
https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/forward/bst_openmeeg.m#L76

Should I update this function so it downloads the new packages?

**Comment by eolivi** [comment]
ok I understand. 
No, please wait until we finalize the release.
these new packages are pre-release .

**Comment by ftadel** [comment]
With the help of the user reporting this issue, I realized that there was an error in the Brainstorm function bst_openmeeg.m. The combination of ECOG sensors with the option "Use adjoint formulation" was not working. It's fixed now.
