### ISSUE TITLE
SEEG forward model, error #134

### ISSUE THREAD

**Issue by ftadel** [openmeeg/openmeeg#179]
See the following threads on the Brainstorm forum:
http://neuroimage.usc.edu/forums/showthread.php?2840-SEEG-forward-model-error-using-OpenMEEG
http://neuroimage.usc.edu/forums/showthread.php?2767-openmeeg-error
http://neuroimage.usc.edu/forums/showthread.php?1089-OpenMEEG-error-134

**Comment by eolivi** [comment]
thank you for reporting issues.
sadly without any data I cannot reproduce the error.
We are planning very soon a new release of OpenMEEG on all platforms.
I have just uploaded a Win64 executable at the usual location (see README.rst). This executable is not yet fully tested (it is not the release version yet), but may help you. I don't have any 32bit version for now.
But please provide us your data so that we can investigate.

**Comment by ftadel** [comment]
I will ask our users to send example datasets.

I'm not sure Brainstorm is currently using the latest versions of OpenMEEG for the different platforms.
It download the program from the following URLs:
https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/forward/bst_openmeeg.m#L76

**Comment by ftadel** [comment]
The option "Use adjoint formulation" is currently not compatible with SEEG electrodes in Brainstorm.
The OpenMEEG functions that were called referred to non-existing files.

**Without this adjoint option (works)**
`om_assemble -HM "openmeeg.geom" "openmeeg.cond" "openmeeg_hm.mat"
om_minverser "openmeeg_hm.mat" "tess_innerskull_bem_362V_openmeeg.mat"
om_assemble -DSM "openmeeg.geom" "openmeeg.cond" "openmeeg_dipoles.txt" "openmeeg_dsm.mat"
om_assemble -H2IPM "openmeeg.geom" "openmeeg.cond" "openmeeg_loc_seeg.txt" "openmeeg_h2ipm.mat"
om_assemble -DS2IPM "openmeeg.geom" "openmeeg.cond" "openmeeg_dipoles.txt" "openmeeg_loc_seeg.txt" "openmeeg_ds2ipm.mat"
om_gain -IP "tess_innerskull_bem_362V_openmeeg.mat" "openmeeg_dsm.mat" "openmeeg_h2ipm.mat" "openmeeg_ds2ipm.mat" "openmeeg_gain_seeg.mat"`

**With the adjoint option**
om_assemble -HM "openmeeg.geom" "openmeeg.cond" "tess_innerskull_bem_362V_openmeeg.mat"
om_assemble -H2IPM "openmeeg.geom" "openmeeg.cond" "openmeeg_loc_seeg.txt" "openmeeg_h2ipm.mat"
om_assemble -DS2IPM "openmeeg.geom" "openmeeg.cond" "openmeeg_dipoles.txt" "openmeeg_loc_seeg.txt" "openmeeg_ds2ipm.mat"

How should I call om_gain in this second case?

**Comment by eolivi** [comment]
actually the adjoint formulation is only coded for the computation of the leadfields of:
- EEG
- MEEG
- EEG&MEG (simultaneously)
The adjoint method was not coded for IP leadfields although this could be a feature-request if our users want it.
Can we close or change the title into a feature-request (if needed) ?

**Comment by ftadel** [comment]
It works for ECOG too, I guess this is considered as EEG.
I removed the invalid combination of options SEEG+adjoint, so the bug is gone.
Thanks

**Comment by mclerc** [comment]
Going for adjoint with sEEG is theoretically possible using the methodology explained in https://www.ncbi.nlm.nih.gov/pubmed/19075359
but it hasn't been implemented yet...
