### ISSUE TITLE
CMake issues

### ISSUE THREAD

**Issue by mclerc** [openmeeg/openmeeg#21]
- Modify tests/CMakeLists.txt for comparing the non nested models NNa1, NNb1 and NNc1 when the user did not specify (USE_VTK). (( These non-nested models are run but not compared with analytical solutions (due to the architecture of the file tests/CMakeLists.txt) ))
- Solve CMake warnings at configuration step, such as CPack.cmake included twice (clapack/CMakeLists.txt)

**Comment by agramfort** [comment]
I think it's ok now
