### ISSUE TITLE
lib issue when using openmeeg with Brainstorm in matlab

### ISSUE THREAD

**Issue by zhengchencai** [openmeeg/openmeeg#220]
Hi, 
I got the following issue related to lib I guess when I was trying to calculate the BEM model for EEG in Brainstorm. Could you please help ? Thank you very much

![image](https://user-images.githubusercontent.com/29985544/27969887-ba91d252-631a-11e7-82e8-597c3ff4b87c.png)

Best regards,
Zhengchen

**Comment by agramfort** [comment]
hi,

why version of openmeeg are you using?

we're about to make a new release. Maybe can you test if our new binaries:

http://openmeeg.gforge.inria.fr/download/OpenMEEG-2.3.99.0-Win64-OpenBLAS-OpenMP-vtk-python.tar.gz

fix your problem?

thanks for reporting any issue with these new binaries.

**Comment by thomasbeaudry** [comment]
Hi,
I am the sysadmin zhengchai.  Can we get a link to the Linux (Ubuntu) version of the latest release? 
Thanks,
Thomas

**Comment by eolivi** [comment]
hi,
here is what we have so far
http://openmeeg.gforge.inria.fr/download/

the linux binaries are not standalone (yet),  it does not include the openblas nor matio nor hdf5. (if the user has it, then it should be working)

**Comment by agramfort** [comment]
Should be fixed by latest brainstorm version.
