### ISSUE TITLE
fix regression -H2ECOGM option.

### ISSUE THREAD

**Issue by agramfort** [openmeeg/openmeeg#241]
master breaks 2.2 H2ECOGM option due to a change of number of parameters.

we need a proper deprecation cycle eg by supporting both versions and show a warning when only 4 parameter are passed.

cc @ftadel @papadop @mclerc

**Comment by agramfort** [comment]
by looking at the code I even this that the option "-Head2ECoGMat", "-H2ECogM", "-H2ECOGM", "-h2ecogm" is not even tested...

[ecog_model.zip](https://github.com/openmeeg/openmeeg/files/1289672/ecog_model.zip)

I put here the model with my debug.sh script. You see that I have to write:

om_assemble -H2ECOGM openmeeg.geom openmeeg.cond openmeeg_loc_ecog.txt 3 openmeeg_h2ecogm.mat

to make it work. The value 3 is a mystery to me as no "Interface" is called 3...

@papadop can you please have look?

**Comment by eolivi** [comment]
hello,
just by looking at the .geom (old style geom) as no name are given for the interfaces (old style geom), they will be numbered (called) by order like this:

1 openmeeg_2.tri                  
2 openmeeg_3.tri                  
3 openmeeg_1.tri   

in the ECOG assembly, the name of the interface must be given (as a string).
Thus if you give the "3" it means you're giving the  "openmeeg_1.tri" as the mesh were the Ecog electrodes are placed.

the domains are defined like this:
Domain Scalp 1 -3
Domain Skull 2 -1
Domain Brain -2   
Domain Air 3           

thus the "3" interface (=mesh) is the scalp/skull interface (IMO maybe not the right one for EcoG it should be brain/skull interface ? thus number "2"=openmeeg_3.tri )

**Comment by agramfort** [comment]
thx @eolivi 

@eolivi do you see a way to release without breaking code? ie with a deprecation warning.

**Comment by papadop** [comment]
Done
