### ISSUE TITLE
travis ICC setup

### ISSUE THREAD

**Issue by agramfort** [openmeeg/openmeeg#251]
we could try to use:

https://github.com/nemequ/icc-travis

to build OpenMEEG using ICC + MKL to have optimal performance
for our release binaries.

**Comment by papadop** [comment]
Well, we can split this in two parts. ICC and MKL. For MKL, there is work in progress.
ICC is another beast. 1) I think it requires a licence, so this is more complicated. 2) Not so sure it will be much faster than gcc with the proper options. 3) Do not know the result speed on AMD processors (which are again attractive nowadays).

**Comment by agramfort** [comment]
@massich is taking a look these days. I agree than MKL without ICC would already be great.

**Comment by papadop** [comment]
Have a look at my PR of yesterday. It works on my computer. Not yet on travis, and I know that there are some adjustments to do for windows and MacOs. But most of the infrastructure is there. See also my other issue on using ilp64 with MKL to allow for matrices of more than 2GB.

**Comment by papadop** [comment]
The branch is on origin not in the papadop clone.

**Comment by massich** [comment]
I wrote a MWE . I'm able to link against MKL and openblas locally. Right now I'm trying to mimic this in travis-ci.

**Comment by massich** [comment]
@papadop look at https://travis-ci.org/massich/cpp-mkl-test/builds

I've also plugged into a travis container locally and work there and it seems to work.

**Comment by massich** [comment]
https://github.com/massich/cpp-mkl-test

**Comment by massich** [comment]
For completeness: 
Compiling using INTEL_SERIAL_NUMBER secret, wont be available in PR (only on merge to master). So the intel enviornment should either be deactivated at PR.[see this example](https://github.com/LLNL/RAJAPerf/blob/ebe1647a8c42c296e8e5fef3d67efff0977143e2/.travis.yml#L44)
Or find a manner to silently install the trail version as they do [here](https://github.com/GLEON/GLM-source/blob/e4f6e650e5688247806281efa7804a479cf66468/install-icc.sh#L142)

**Comment by agramfort** [comment]
does it work if you don't encrypt serial?

**Comment by massich** [comment]
apparently that's what the second project does. But I didn't find how they trigger it, yet.

**Comment by massich** [comment]
> does it work if you don't encrypt serial?

Sorry I missread the question. Yes it installs properly if the serial is encrypted. (It fails somewhere else but it installs properly)  [See this build of the ICC PR](https://travis-ci.org/openmeeg/openmeeg/builds/305164442#L550) where the icc compiler is properly installed and found.

**Comment by larsoner** [comment]
Travis is gone, closing
