### ISSUE TITLE
clang is never used in travis CI (under linux)

### ISSUE THREAD

**Issue by massich** [openmeeg/openmeeg#255]
https://github.com/openmeeg/openmeeg/blob/8034af9cca309bed83107c038286554363e78862/build_tools/travis/before_install.sh#L61-L66

**Comment by papadop** [comment]
Not sure to understand. There is a linux build with clang (at least this is how it is said in the travis.yml file). Do you say that because travis.yml says clang and here the CXX variable is compared to clang++ ?

**Comment by massich** [comment]
It seems that regardless of the matrix's variable, CXX it is hard set to g++ just before checking.

**Comment by papadop** [comment]
OK. Will have a look at correcting that....

**Comment by massich** [comment]
No worries #254 is related
