### ISSUE TITLE
travis configuration errors

### ISSUE THREAD

**Issue by massich** [openmeeg/openmeeg#256]
lint.travis-ci.org, is a service that checks `.travis.yml` configurations. It screems on us!
https://lint.travis-ci.org/openmeeg/openmeeg

**Comment by agramfort** [comment]
yes apparently env needs to fit in one line eg:

language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: osx
      compiler: clang
      env:
        - USE_SYSTEM=0 USE_PROJECT=1 USE_VTK=1
BLASLAPACK_IMPLEMENTATION=Auto # (Auto is the same as MKL/OpenBLAS/vecLib
in priority)

before_install: source build_tools/travis/before_install.sh

install: source build_tools/travis/install.sh

script: source $TRAVIS_BUILD_DIR/build_tools/travis/script.sh

after_success: source $TRAVIS_BUILD_DIR/build_tools/travis/after_success.sh

**Comment by agramfort** [comment]
this works tool

language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: osx
      compiler: clang
      env:
        - USE_SYSTEM=0 \
          USE_PROJECT=1 \
          USE_VTK=1 \
          BLASLAPACK_IMPLEMENTATION=Auto

before_install: source build_tools/travis/before_install.sh

install: source build_tools/travis/install.sh

script: source $TRAVIS_BUILD_DIR/build_tools/travis/script.sh

after_success: source $TRAVIS_BUILD_DIR/build_tools/travis/after_success.sh
