### ISSUE TITLE
Build on Fedora 27

### ISSUE THREAD

**Issue by papadop** [openmeeg/openmeeg#277]
Trying to build on Fedora after today's merge...
Not sure, I will have time to correct the issues, so I'm logging them here.
Sources obtained from github commit c2913321d923b4aefbfd3f3a726cf0eb7f88be38
Stock fedora 27 machine with lapack installed :
/usr/lib64/liblapack.so
/usr/lib64/liblapacke.so
among others.

New build:
andaman-> cmake ~/src/openmeeg/
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check whether the compiler implements namespaces
-- Check whether the compiler implements namespaces - found
-- Check whether the compiler has isnormal function in namespace std
-- Check whether the compiler has isnormal function in namespace std - found
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
CMake Error at cmake/thirdParties.cmake:48 (message):
  BLA_VENDOR Unset.  Please Specify a library
Call Stack (most recent call first):
  CMakeLists.txt:20 (include)

No BLA_VENDOR is appearing in the cmake variables. The option does not exist anymore....
bali-> fgrep -r BLA_VENDOR
cmake/thirdParties.cmake:if (BLA_VENDOR MATCHES Intel)
cmake/thirdParties.cmake:    if (BLA_VENDOR MATCHES "_seq")
cmake/thirdParties.cmake:elseif(BLA_VENDOR MATCHES OpenBLAS) # XXX: OpenBLAS should be set up using find_package(BLAS)
cmake/thirdParties.cmake:    if (BLA_VENDOR MATCHES ATLAS)
cmake/thirdParties.cmake:    elseif(BLA_VENDOR MATCHES Apple)
cmake/thirdParties.cmake:    elseif(BLA_VENDOR MATCHES "")
cmake/thirdParties.cmake:        message(FATAL_ERROR "BLA_VENDOR Unset. Please Specify a library")
.travis.yml:      export CMAKE_OPTIONS="-DCMAKE_CXX_STANDARD=11 -DBLA_VENDOR=$BACKEND"
.travis.yml:      export CMAKE_OPTIONS="-DCMAKE_CXX_STANDARD=11 -DBLA_VENDOR=$BACKEND -DENABLE_COVERAGE=ON"
.appveyor.yml:  - "ECHO 'cmake -DBLA_STATIC=%BUILD_STATIC% -DBLA_VENDOR=%BLAS_VERSION% -G \"Visual Studio 14 2015 Win64\" .. '"
.appveyor.yml:  - cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBLA_STATIC=%BUILD_STATIC% -DBLA_VENDOR=%BLAS_VERSION% -G "Visual Studio 14 2015 Win64" ..

I went back to a previous version (I have no time to correct the problem now). I received these warnings: 
CMake Warning at libs/OpenMEEG/src/CMakeLists.txt:11 (add_library):
  Cannot generate a safe runtime search path for target OpenMEEG because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libexpat.so.1] in /usr/lib64 may be hidden by files in:
      /user/ikojcic/home/miniconda3/lib
    runtime library [libz.so.1] in /usr/lib64 may be hidden by files in:
      /user/ikojcic/home/miniconda3/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  libs/OpenMEEG/src/CMakeLists.txt:38 (create_library)

Which seems to show a dangerous interaction with miniconda on that computer, but that's probably not OpenMEEG fault.

**Comment by agramfort** [comment]
@papadop yes you should not source anaconda if you don't plan to use it
with cmake.

also can you try with openblas?

cmake -DBLA_VENDOR=OpenBLAS ..

**Comment by papadop** [comment]
Yes, but can someone add BLA_VENDOR (or another better name) as an option that appears in ccmake ?
Forcing the need of the option on the command line is not very developer friendly...

For the anaconda, that's maybe not a big deal. After all, it is just a warning... that being said, it was not my environment and students (or non very technical users) tends to source things in their .bashrc .... But I guess the problem was already there before.... I was first worried because I thought it was a consequence of using conda for travis and appveyor....

**Comment by agramfort** [comment]
agreed

we should try to provide a good default for BLA_VENDOR on all platforms:

- OpenBLAS on linux
- Apple on mac
- MKL on windows

**Comment by papadop** [comment]
I think it's done...
