### ISSUE TITLE
libOpenMEEG soname

### ISSUE THREAD

**Issue by sagitter** [openmeeg/openmeeg#281]
Hello.

With new build system, is `libOpenMEEG`'s soname still considered?

**Comment by agramfort** [comment]
do you think we should?  what do you suggest?

**Comment by sagitter** [comment]
`soname` were already created with old `cmake`'s build system. They may be useful to provide version compatibility information to the system, especially from my point of view, i will provide OpenMEEG libraries inside RPM packages for Fedora.

**Comment by agramfort** [comment]
ok sounds good.

can you send us a PR?

**Comment by sagitter** [comment]
I'm not accustomed to this type of modifications.
Sorry.

**Comment by agramfort** [comment]
see https://github.com/openmeeg/openmeeg/pull/282
