### ISSUE TITLE
OpenMEEG packaging for Fedora

### ISSUE THREAD

**Issue by sagitter** [openmeeg/openmeeg#290]
Hello everyone.

Just to annotate that `OpenMEEG` is now packed for `Fedora 27+` as RPM package: https://src.fedoraproject.org/rpms/openmeeg

**Comment by agramfort** [comment]
awesome. thanks very much.

can you send a PR to add a line to our readme.rst to say how to install
openmeeg on fedora?
just below the mention to debian / neurodebian.

thanks again

**Comment by sagitter** [comment]
Yes, as soon as i fixed build process for CentOS too.

**Comment by massich** [comment]
@sagitter can I close?

**Comment by sagitter** [comment]
@massich 
Sorry, i missed this thread.

@agramfort 

> can you send a PR to add a line to our readme.rst to say how to install openmeeg on fedora? just below the mention to debian / neurodebian.

Really easy:

On Fedora

`# dnf install openmeeg openmeeg-devel python2-openmeeg`

On RHEL/CentOS 7, enable [EPEL repositories](https://fedoraproject.org/wiki/EPEL) and install

`# yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`
`# yum install openmeeg openmeeg-devel python2-openmeeg`

Additional repositories recommended on RHEL 7

`# subscription-manager repos --enable "rhel-*-optional-rpms" --enable "rhel-*-extras-rpms"`

**Comment by agramfort** [comment]
cool

@massich can you update the readme accordingly?

thx
