### ISSUE TITLE
Unusual workflow of CTest

### ISSUE THREAD

**Issue by massich** [openmeeg/openmeeg#316]
The usual way to use CTest is to include CTest and then use `BUILD_TESTING` exposed by `find_package(Ctest)` to drive `enable_testing()`. In our codebase we just set it to true and enable testing.

https://github.com/openmeeg/openmeeg/blob/11d1db77dcb07107e17e747f8559324897926a89/cmake/options.cmake#L1-L2

**Comment by agramfort** [comment]
do you have an example of good practice?

**Comment by papadop** [comment]
Hopefully handled with PR #560.

**Comment by papadop** [comment]
Done. PR #560 merged.
