### ISSUE TITLE
global CXX standard

### ISSUE THREAD

**Issue by massich** [openmeeg/openmeeg#319]
https://github.com/openmeeg/openmeeg/blob/ad40007b24f83afca1fae8ee5d90d89fac6ffa7f/CMakeLists.txt#L4

I would propagate this option to the targets. I'm more inclined to use a list of required compiler features, but I agree that this can end up being tedious to maintain. 

I'm in favor of splitting the code in targets and set brought compiler options to a target level. See [this](https://crascit.com/2015/03/28/enabling-cxx11-in-cmake/)

**Comment by agramfort** [comment]
+1

**Comment by papadop** [comment]
It is much easier to use a given level of standard for all of the code. Setting standard level per target will be tedious for no real advantage (as of today). More stuff to handle and over all, we will have to check for each target what is the required standard level !!! Not speaking of how to deal with files that are included in multiple targets. So let's keep an homogeneous situation (which by the way was bumped to c++-17). We can still use the target way to make experiments with a specific target (temporarily).

Note also that C++ have features' macros which can be used directly to test the existence of a feature within the code (so no cmake complicated stuff to handle).
