### ISSUE TITLE
Move header files into directories to avoid name colision

### ISSUE THREAD

**Issue by massich** [openmeeg/openmeeg#324]
see https://github.com/conda-forge/staged-recipes/pull/5534#issuecomment-400375289

**Comment by agramfort** [comment]
indeed... should the headers be also in the main source tree in
OpenMEEG/ and OpenMEEGMaths/ folders? then we should just install the
2 folders?

**Comment by massich** [comment]
I don't even think its necessary. IOW, if we define properly what should and should not be public we might avoid the conflict. I don't think that we should expose `exception.h` or `vector.h`. Who would be calling it?

once said that, IMHO, I also think that we should do folders (and probably renaming).

**Comment by agramfort** [comment]
Ok. Propose me something and we iterate

**Comment by papadop** [comment]
Calling no.... But catching yes, so they might want to call the methods to get the messages... That being said, if it's only the virtual what and everything correctly derives from std::exception, it might indeed not be necessary. Yet someone using the library might want to catch some specific error and thus would need at least a declaration of the possible exceptions, so my guess is that the easiest is to provide the include.

Looking at the message referenced above, I did not see where is the conflict. OpenMEEGMaths and OpenMEEG includes should end up in the same directory in the end... At least that was how it was before I split OpenMEEGMaths  (and all libs) in their own directory to - hopefully - clearly differentiate/modularize the code (or at least clarify to some extent).

**Comment by agramfort** [comment]
@papadop do you agree to do some changes so people import openmeeg headers
with a prefix like OpenMEEG/exceptions.h ?

**Comment by papadop** [comment]
What is the problem that is to be solved ? Why not simply OpenMEEG/OpenMEEEGMaths/Exceptions.H
In any case, we probably will ditch/revisit that sooner or later when we migrate to xtensor...

**Comment by agramfort** [comment]
the pb is that we should not install the openmeeg headers in the
general include folder but in an OpenMEEG subfolder.

**Comment by papadop** [comment]
Definitely. they should be in /usr/include/OpenMEEG and I'd be in favor of having a further subdirectory OpenMEEGMaths to clearly distinguish those . An old tgz of mine shows that includes were installed in /usr/include/openmeeg/ (but unfortunately no OpenMEEGMaths subdirectory everything was installed directly there). So it was like that... I'd be also for OpenMEEG instead of openmeeg (even though it will do nothing on windows and mac).

**Comment by agramfort** [comment]
ok https://github.com/openmeeg/openmeeg/pull/326 fixes the pb.

**Comment by massich** [comment]
Closing, we should reopen when discussing how and when to split the code.
