### ISSUE TITLE
PythonInterp and PythonLibs deprecation in CMake

### ISSUE THREAD

**Issue by massich** [openmeeg/openmeeg#325]
https://github.com/openmeeg/openmeeg/blob/ab4ae10bb860f14e13c1ab19a0681eaf2cf7c973/wrapping/src/CMakeLists.txt#L14-L16

The new syntax is much better and simplifies the issue installing the paths.
https://cmake.org/cmake/help/latest/module/FindPythonLibs.html

**Comment by papadop** [comment]
This has been handled a while ago. Closing.
