### ISSUE TITLE
Consider using  CMAKE_INSTALL_OPENMP_LIBRARIES

### ISSUE THREAD

**Issue by jcfr** [openmeeg/openmeeg#332]
https://github.com/openmeeg/openmeeg/blob/48fb8272f8d4ac88b09cce0c776c48fc483de27a/CMakeLists.txt#L50-L53

See https://cmake.org/cmake/help/latest/module/InstallRequiredSystemLibraries.html

**Comment by papadop** [comment]
This has been done with commit 5ce0db80a.
Thank you for the suggestion. Closing the issue.
