### ISSUE TITLE
error if center of interface is in the negative domain

### ISSUE THREAD

**Issue by DanielMiklody** [openmeeg/openmeeg#350]
On a surely closed interface I get the following error:
> Interface "3" is not closed ! 
> Please correct a mesh orientation when defining the interface in the geometry file. 

The bbcenter is out of the interface, due to an erroneous bounding box.
In interface.cpp the xmax,ymax and zmax are wrongly initialized to the numerical minimum, which is close to zero and not to minus infinity. This leads to erroneous bounding boxes if the center of an interface is in the negative domain for any coordinate. I have a branch solving this and will file a pull request, soon.

**Comment by agramfort** [comment]
thanks. I'll review your PR.

>
