### ISSUE TITLE
rebert 4b9b9d4 with a proper way of uploading to gforge

### ISSUE THREAD

**Issue by massich** [openmeeg/openmeeg#359]
We removed this because it was failing in master. This means that we are no longer shipping master builds. This needs to be fixed. Most properly the best way to do that now is using github actions.

https://github.com/openmeeg/openmeeg/commit/4b9b9d453b979baf94f76266bf3731addda49111#commitcomment-32934240

**Comment by papadop** [comment]
gforge is now shut down. There is another repository used for which uploading is also an issue. There are plans for using GH releases instead. As gforge is now dead, I'm closing this issue.
