### ISSUE TITLE
CI Windows7+VTK(+HDF5)

### ISSUE THREAD

**Issue by eolivi** [openmeeg/openmeeg#36]
Resolve the compilation error:
C:\builds\workspace\openmeeg_build_windows7_64_MKL_VTK\contrib\matio\contrib\hdf5\src\H5FDlog.c(508): error C2057: expected constant expression
probably due to H5_HAVE_GETHOSTNAME which is define as 1 by VTK at:
vtk/Utilities/vtkhdf5/src/H5detect.c:323
and used later by matio:
contrib/matio/contrib/hdf5/config/cmake/ConfigureChecks.cmake

build 1180 was done without VTK 
https://ci.inria.fr/openmeeg/job/openmeeg_build_windows7_64_MKL_VTK/1180/consoleText
check the difference with another log with vtk, such as:
https://ci.inria.fr/openmeeg/job/openmeeg_build_windows7_64_MKL_VTK/1182/consoleText

@papadop une idée ?

**Comment by agramfort** [comment]
@eolivi can I close this?

**Comment by eolivi** [comment]
...
