### ISSUE TITLE
migrate to LGTMApp

### ISSUE THREAD

**Issue by massich** [openmeeg/openmeeg#365]
See https://lgtm.com/blog/announcing_github_apps_migration

I tried to migrate (and it seemed it worked) but it keeps complaining. @agramfort can you check if you get the banner in https://lgtm.com/projects/g/openmeeg/openmeeg/alerts/?mode=tree and if so, install it (it does it alone, just asks you which repo which should be there already)

**Comment by agramfort** [comment]
for me it's installed
https://github.com/organizations/openmeeg/settings/installations/999737

**Comment by massich** [comment]
yes it seems like it. Then I've no idea why is complaining. Because I manage to get it in the checks tab of Github. 

Anyways, I'll close this and reopen if the warning does not go a way in the future.
