### ISSUE TITLE
Use of the massich conda channel

### ISSUE THREAD

**Issue by papadop** [openmeeg/openmeeg#386]
I slightly worried by the use of a "personal" account as the conda channel for matio. This is probably a temporary solution, but until the official matio integrates a cmake build and we switch to that official version, I'm worried that it might not be as simple as possible to update matio (need to create a new channel and track all places where it is used).

As I said it is only a slight concern. I would really be happy to learn that it is not a problem in practise.... and that nothing is to be done.

**Comment by massich** [comment]
I guess that this has become priority. Since its what is breaking our windows builds. It works on my machine but it fails in the CIs.

**Comment by larsoner** [comment]
We no longer need/use this
