### ISSUE TITLE
error: template with C linkage

### ISSUE THREAD

**Issue by sagitter** [openmeeg/openmeeg#411]
Hi all.

`Openmeeg-2.4.2` pre-release does not compile on Fedora with following errors:

```
[  1%] Building CXX object OpenMEEGMaths/CMakeFiles/OpenMEEGMaths.dir/src/utils.cpp.o
cd /builddir/build/BUILD/openmeeg-2.4.2/build/OpenMEEGMaths && /usr/bin/c++  -DHAVE_BLAS -DHAVE_LAPACK -DOpenMEEGMaths_EXPORTS -DUSE_OPENBLAS -I/builddir/build/BUILD/openmeeg-2.4.2/OpenMEEGMaths/include -I/usr/include/openblas -I/builddir/build/BUILD/openmeeg-2.4.2/OpenMEEGMaths/MATIO::MATIO -I/builddir/build/BUILD/openmeeg-2.4.2/build/OpenMEEGMaths -I/builddir/build/BUILD/openmeeg-2.4.2/build -I/builddir/build/BUILD/openmeeg-2.4.2/OpenMEEGMaths/OpenMEEGMaths/src  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNDEBUG -fPIC   -std=gnu++11 -o CMakeFiles/OpenMEEGMaths.dir/src/utils.cpp.o -c /builddir/build/BUILD/openmeeg-2.4.2/OpenMEEGMaths/src/utils.cpp
In file included from /usr/include/c++/10/bits/stringfwd.h:40,
                 from /usr/include/c++/10/iosfwd:39,
                 from /usr/include/c++/10/ios:38,
                 from /usr/include/c++/10/istream:38,
                 from /usr/include/c++/10/sstream:38,
                 from /usr/include/c++/10/complex:45,
                 from /usr/include/openblas/lapack.h:58,
                 from /usr/include/openblas/lapacke.h:37,
                 from /builddir/build/BUILD/openmeeg-2.4.2/OpenMEEGMaths/include/BlasLapackImplementations/OpenMEEGMathsOpenBLASConfig.h:10,
                 from /builddir/build/BUILD/openmeeg-2.4.2/OpenMEEGMaths/include/OpenMEEGMathsConfig.h:87,
                 from /builddir/build/BUILD/openmeeg-2.4.2/OpenMEEGMaths/include/RC.H:5,
                 from /builddir/build/BUILD/openmeeg-2.4.2/OpenMEEGMaths/src/utils.cpp:40:
/usr/include/c++/10/bits/memoryfwd.h:63:3: error: template with C linkage
   63 |   template<typename>
      |   ^~~~~~~~
In file included from /usr/include/openblas/lapacke.h:37,
                 from /builddir/build/BUILD/openmeeg-2.4.2/OpenMEEGMaths/include/BlasLapackImplementations/OpenMEEGMathsOpenBLASConfig.h:10,
                 from /builddir/build/BUILD/openmeeg-2.4.2/OpenMEEGMaths/include/OpenMEEGMathsConfig.h:87,
                 from /builddir/build/BUILD/openmeeg-2.4.2/OpenMEEGMaths/include/RC.H:5,
                 from /builddir/build/BUILD/openmeeg-2.4.2/OpenMEEGMaths/src/utils.cpp:40:
/usr/include/openblas/lapack.h:16:1: note: 'extern "C"' linkage started here
   16 | extern "C" {
      | ^~~~~~~~~~
```

GCC-10.0.1
openblas-0.3.9
Full build log: [here](https://kojipkgs.fedoraproject.org//work/tasks/5994/42255994/build.log)

**Comment by agramfort** [comment]
for @papadop

>

**Comment by papadop** [comment]
Thank's for the report....

As far as I can tell, this is possibly not an OpenMEEG problem. It seems to involve openblas/lapack.h which either has an unclosed extern "C" or includes some C++ header in that extern "C" section.  There may be some changes in openblas that require us to do some adaptation in openmeeg to avoid that, but for now I stucked with fedora-31. If I understand well, you are are involved in providing the openmeeg package for the upcoming fedora-32 release (the go for fedora-32 was only yesterday or the day before as far as I can tell).

I have not found any web ressources ob changes between OpenBlas 0.3.9 and OpenBlas 0.3.7 (which is the fedora 31 version I currently use).

OpenBlas 0.3.9 seems to currently be in testing (for fedora 31 and fedora 32). I'll try to install that version, so I hope to be able to test further soon....

**Comment by papadop** [comment]
OK. I can reproduce the buf by installing openblas 0.3.9 on fedora 31.

**Comment by papadop** [comment]
Confirmed it's a bug in openblas which does:
`#ifdef __cplusplus
extern "C" {
#endif
[....]
#ifndef LAPACK_COMPLEX_CUSTOM

/* Complex type (single precision) */
#ifndef lapack_complex_float
#ifndef __cplusplus
#include <complex.h>
#else
#include <complex>
#endif
#define lapack_complex_float    float _Complex
`
It may be possible to work around the problem using LAPACK_COMPLEX_CUSTOM but I'd prefer that openblas 0.3.9 is corrected as it is obviously wrong. Making a report (and a patch on their git repo in a minute....

**Comment by papadop** [comment]
Actually, it is already corrected by commit 51019feae1f65a22075c4d28efcabdbb35cd2c6f.
And 0.3.9 is not even tagged on git.... So I guess the best thing is to wait the openblas 0.3.9 packages grabs the last changes, which will correct the problem with openmeeg....

**Comment by papadop** [comment]
Let's leave this report open till we have the confirmation that an update of 0.3.9 corrects the reported problem.

**Comment by papadop** [comment]
I think that the problem should now be fixed. Several fedora builds were done recently. And openblas version is now 0.3.19 on fedora 36. Closing.
