### ISSUE TITLE
Error When I Attempt Build OpenMEEG from source on Ubuntu

### ISSUE THREAD

**Issue by trabulsim** [openmeeg/openmeeg#418]
When I enter the following line:

cmake -DCMAKE_BUILD_TYPE=Release -DUSE_PROGRESSBAR=ON -DBLA_VENDOR=OpenBLAS ..

I get this:

CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS) (found
  version "")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindHDF5.cmake:929 (find_package_handle_standard_args)
  cmake/Findmatio.cmake:20 (find_package)
  cmake/thirdParties.cmake:59 (find_package)
  CMakeLists.txt:20 (include)

I tried to install HDF5 and it didn't work too

**Comment by papadop** [comment]
This is strange. We build regularly on Ubuntu. Which Ubuntu version do you use ? 
You may need hdf5-dev (and matio-dev), though I though that if hdf5 was not available, we just disabled the matio support.

Note also that openmeeg is already package for debian/Ubuntu.
http://neuro.debian.net/pkgs/openmeeg-tools.html
If you just need to use OpenMEEG (ie not developping/modifying OpenMEEG code), that might be a solution.

**Comment by trabulsim** [comment]
> This is strange. We build regularly on Ubuntu. Which Ubuntu version do you use ?
> You may need hdf5-dev (and matio-dev), though I though that if hdf5 was not available, we just disabled the matio support.
> 
> Note also that openmeeg is already package for debian/Ubuntu.
> http://neuro.debian.net/pkgs/openmeeg-tools.html
> If you just need to use OpenMEEG (ie not developping/modifying OpenMEEG code), that might be a solution.

I have Ubuntu 20.04

I am trying to use OpenMEEG with Fieldtrip toolbox and I was told that the binaries were missing so I attempted to install it
