### ISSUE TITLE
Issue Installing from Neuro Debian on Ubuntu 20.04

### ISSUE THREAD

**Issue by trabulsim** [openmeeg/openmeeg#419]
Hello
I followed the steps on this link:
http://neuro.debian.net/pkgs/openmeeg-tools.html

When I try install openmeeg tools using this command:
sudo apt-get install openmeeg-tools

I get the following error:
Package openmeeg-tools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'openmeeg-tools' has no installation candidate

**Comment by agramfort** [comment]
the open neuro package is very outdated I think

>

**Comment by papadop** [comment]
PR merged. Closing.
