### ISSUE TITLE
ctest  command is failing in Openmeeg with LTO optimization

### ISSUE THREAD

**Issue by sagitter** [openmeeg/openmeeg#420]
Hi all.

A lot of tests (Openmeeg 2.4.2) are failing with `ctest-3.18.1` with an error like this:

```
591: Test command: /builddir/build/BUILD/openmeeg-2.4.2/build/tests/test_compare_matrix "/builddir/build/BUILD/openmeeg-2.4.2/build/tests/HeadNNb2-dip.est_eegadjoint2" "/builddir/build/BUILD/openmeeg-2.4.2/tests/analytic/eeg_head2_analytic.txt" "-rdm" "-eps" "0.1" "-col" "5" "-full"
/builddir/build/BUILD/cmake-3.18.1/Source/cmCTest.cxx:303    Current_Time: Aug 04 14:25 UTC
/builddir/build/BUILD/cmake-3.18.1/Source/CTest/cmCTestRunTest.cxx:714 591: Test timeout computed to be: 10000000
/builddir/build/BUILD/cmake-3.18.1/Source/CTest/cmCTestRunTest.cxx:41 591: -------------------------------------------------
/builddir/build/BUILD/cmake-3.18.1/Source/CTest/cmCTestRunTest.cxx:41 591: Comparing : 
/builddir/build/BUILD/cmake-3.18.1/Source/CTest/cmCTestRunTest.cxx:41 591: - /builddir/build/BUILD/openmeeg-2.4.2/build/tests/HeadNNb2-dip.est_eegadjoint2
/builddir/build/BUILD/cmake-3.18.1/Source/CTest/cmCTestRunTest.cxx:41 591: - /builddir/build/BUILD/openmeeg-2.4.2/tests/analytic/eeg_head2_analytic.txt
/builddir/build/BUILD/cmake-3.18.1/Source/CTest/cmCTestRunTest.cxx:41 591: Cannot open file /builddir/build/BUILD/openmeeg-2.4.2/build/tests/HeadNNb2-dip.est_eegadjoint2 !
/builddir/build/BUILD/cmake-3.18.1/Source/CTest/cmCTestRunTest.cxx:871  591/1188 Test  #591: cmp-EEGadjoint2EST-dip-HeadNNb2-dip5-rdm ......
/builddir/build/BUILD/cmake-3.18.1/Source/CTest/cmCTestRunTest.cxx:874 Testing cmp-EEGadjoint2EST-dip-HeadNNb2-dip5-rdm ... 
/builddir/build/BUILD/cmake-3.18.1/Source/CTest/cmCTestRunTest.cxx:220 ***Failed    0.01 sec
/builddir/build/BUILD/cmake-3.18.1/Source/CTest/cmCTestRunTest.cxx:224 -------------------------------------------------
Comparing : 
- /builddir/build/BUILD/openmeeg-2.4.2/build/tests/HeadNNb2-dip.est_eegadjoint2
- /builddir/build/BUILD/openmeeg-2.4.2/tests/analytic/eeg_head2_analytic.txt
Cannot open file /builddir/build/BUILD/openmeeg-2.4.2/build/tests/HeadNNb2-dip.est_eegadjoint2 !
/builddir/build/BUILD/cmake-3.18.1/Source/cmCTest.cxx:303    Current_Time: Aug 04 14:25 UTC
/builddir/build/BUILD/cmake-3.18.1/Source/CTest/cmCTestMultiProcessHandler.cxx:167 test 592
/builddir/build/BUILD/cmake-3.18.1/Source/CTest/cmCTestRunTest.cxx:481           Start  592: cmp-EEGEST-dip-HeadNNc1-dip5-mag
/builddir/build/BUILD/cmake-3.18.1/Source/CTest/cmCTestRunTest.cxx:649 
```

Full build log: https://kojipkgs.fedoraproject.org//work/tasks/2958/48632958/build.log

**Comment by sagitter** [comment]
The reported error seems coming out when we use the [LTO flags](https://fedoraproject.org/wiki/LTOByDefault) (by default in Fedora 33+): `-flto=auto -ffat-lto-objects`

**Comment by papadop** [comment]
I have seen on fedora that there were a lot of problems which were compiler related, and that some compiler adjustments were made. As I have only the f32 compiler can you confirm the bug is still present ? We sometimes play some weird games with linking, but in the fedora case I would expect using standard shared libraries, so OpenMEEG should not be any different to many other softwares.

If the problem still happens, I will try to compile a newer gcc and to find out where the problem comes from. I need also to re-read Jeff Law email as he monitored quite closely the lto troubles, so the problem we are facing out might have been already reported and solved (or a fix other than disbling LTO proposed).

**Comment by papadop** [comment]
Just a small note for future investigation:

I think I remember there was a problem in LTO with the order of static variables initialization (I remember having seen Jeff Law saying something like that either in the fedora or on the gcc mailist). This is probably related to the problem as we rely on static data member initialization to detect the various file formats backends.

**Comment by larsoner** [comment]
I think builds are working with 2.4.7 now so I'll close
