### ISSUE TITLE
Please don't hint NeuroDebian in README.rst

### ISSUE THREAD

**Issue by b2ag** [openmeeg/openmeeg#428]
According to
http://neurodebian.inm7.de/debian/pool/main/o/openmeeg/
the newest version of OpenMEEG in NeuroDebian is 9 years old.

It's not helpful to say there are precompiled packages in NeuroDebian. I just lost some substantial amount of time by automating an installation of Ubuntu 20.04 plus NeuroDebian only to find out that OpenMEEG is not present. Now I will redo the whole thing with Fedora Linux.

Please spare other people the trouble and at least place a hint saying NeuroDebian OpenMEEG packages are very very old along the line in README.rst.

Thanks!

EDIT: Just found out I'm not the first one fallen for that (#419 )

**Comment by agramfort** [comment]
sorry to hear that. OpenMEEG lacks real maintenance on the packaging side.
I don't have enough time and debian is not in my comfort zone.
Now it's very possible that the code from 9 years ago is still usable
and correct.
Most openmeeg users use binaries I produced a long long time ago...

PR welcome to update the readme

**Comment by b2ag** [comment]
Using old Debian packages on newer Debian versions is asking for trouble.
As a random example `om_mesh_info` from `openmeeg-tools_2.0.0.dfsg-4~nd70+1_amd64.deb` is linked against libraries like `libatlas.so.3gf` which was last available in Debian Jessi (released April 2015). Long term support for Jessi ended June 2020.
On modern Debian/Ubuntu you most probably need to build from source to depend on the correct library versions installed.

I created pull request #429 but I'm not that good with words.

**Comment by papadop** [comment]
The pull request have been merged. Closing this report.
