### ISSUE TITLE
add_library cannot create imported target "HDF5::HDF5" because another target with the same name already exists.

### ISSUE THREAD

**Issue by b2ag** [openmeeg/openmeeg#430]
When trying to compile from source Cmake is complaining about misuse? of add_library.

```
-- Found HDF5: /usr/lib/libhdf5.so;/usr/lib/libsz.so;/usr/lib/libz.so;/usr/lib/libdl.so;/usr/lib/libm.so (found version "1.12.0")
CMake Error at cmake/Findmatio.cmake:39 (add_library):
  add_library cannot create imported target "HDF5::HDF5" because another
  target with the same name already exists.
Call Stack (most recent call first):
  cmake/thirdParties.cmake:59 (find_package)
  CMakeLists.txt:20 (include)
```

Using Arch Linux.

**Comment by agramfort** [comment]
sorry @b2ag but I don't have the bandwidth to investigate this. Let us know if you find a way out

**Comment by papadop** [comment]
I will do that. I'm a little bit puzzled as we do not changed code for a while. It's probably cmake that makes more stringent tests.
Can you tell me your cmake version and the options you use to build OpenMEEG. Being able to reproduce the error is a crucial step for use to correct it. Thank's in advance....

**Comment by b2ag** [comment]
cmake version 3.21.3
cmake -DCMAKE_BUILD_TYPE=Release -DUSE_PROGRESSBAR=ON -DBLA_VENDOR=OpenBLAS ..

**Comment by maedoc** [comment]
Commenting [`cmake/Findmatio.cmake:39`](https://github.com/openmeeg/openmeeg/blob/master/cmake/Findmatio.cmake#L39) avoids the issue.  Perhaps that line can be wrapped in something like `if_not_exists(HDF5::HDF5)` or something.

**Comment by papadop** [comment]
OK. Got it. In recent cmake versions (3.18 and above but not sure on the exact release that introduced it) FindHDF5 already defines the HDF4::HDF5 target.
My first attempt uses: if (${CMAKE_VERSION} VERSION_LESS_EQUAL "3.18")
But your suggestion seems more robust... So the right correction is:
if (NOT TARGET HDF5::HDF5)
Will appear soon with other improvements...

**Comment by papadop** [comment]
Should be commited to master now.
