### ISSUE TITLE
MAINT: Use clang-format

### ISSUE THREAD

**Issue by larsoner** [openmeeg/openmeeg#444]
We can configure this. See

https://github.com/InsightSoftwareConsortium/ITK/blob/master/.clang-format

For an example

I would not add this as commit hook or anything that requires to have clang installed but we should add this to CIs

_Originally posted by @agramfort in https://github.com/openmeeg/openmeeg/issues/392#issuecomment-549017813 but edited by @larsoner_

**Comment by larsoner** [comment]
@papadop do you want to do this at some point when you don't have many PRs open. This one will make conflicts with pretty much any open PR...

**Comment by papadop** [comment]
I'm somewhat reluctant.
Last time I checked those code formatters, I was not able to make them do all what I like.
But they have probably improved by now. So I need to re-check.
The prospect of making conflicts everywhere is not too appealing too.
I need to think more and make tests.

**Comment by larsoner** [comment]
There aren't many open PRs so now might be a good time. Also any branches you planned on making a PR from @papadop you could just run the formatter and it would be okay / help with the conflicts

**Comment by agramfort** [comment]
+1000 to use a code formatter and aim to use it with (almost) defaults assuming it’s used by many big projects

**Comment by larsoner** [comment]
Closing as wontfix until we get more c++ contributors
