### ISSUE TITLE
Failed in CMAKE to compile OpenMEEG with MKL

### ISSUE THREAD

**Issue by vhs304305** [openmeeg/openmeeg#448]
Hello,
I use Visual Studio 2019, CMAKE 3.21.3, MKL 2021.3.0 , and the OpenMEEG source code cloned here on 3/22/2022, in Windows 11.

1. According to the documentation, the only 3rd party dependence is MKL, but the CMAKE have Configure error "Could NOT find HDF5";
2. The CMAKE also show the following errors under BLAS,
BLAS_libguide40_LIBRARY-NOTFOUND
BLAS_libiomp5md_LIBRARY-NOTFOUND
BLAS_mkl_intel_c_dll_LIBRARY-NOTFOUND.

I set the MKLROOT to C:\Program Files (x86)\Intel\oneAPI\mkl\latest.

Please help me to use OpenMEEG in Windows. Thanks.

**Comment by larsoner** [comment]
I think MKL support is pretty broken at the moment. OpenBLAS *almost* works properly. PRs welcome to fix MKL, I am not sure what all would be required...

**Comment by larsoner** [comment]
@vhs304305 our CIs now successfully build on Windows + mingw64 + MKL, feel free to look. MSVC is still a problem but I hope to fix that soon

**Comment by larsoner** [comment]
Closing but feel free to reopen if you see [how our CIs do it](https://github.com/openmeeg/openmeeg/blob/master/.github/workflows/build_and_test.yml) but can't figure it out.

We should update our docs at some point, too, but I think that's a known issue

**Comment by vhs304305** [comment]
Hi Eric,
Thanks for the update. I am not using ming64. I need to set it to x64.
There is another bug in cmake file. It asks for hdf5 but the document
states that the only dependent is mkl.

**Comment by larsoner** [comment]
Our default is now MSVC, and MKL is built with it:

https://github.com/openmeeg/openmeeg/blob/main/.github/workflows/build_and_test.yml#L35

Feel free to look there for inspiration. It uses conda-forge's mkl infrastructure
