### ISSUE TITLE
How to build the head geom and head.cond

### ISSUE THREAD

**Issue by nana-zhang** [openmeeg/openmeeg#483]
Hello, I want to calculate the **gain matrix** of **SEEG**. I just started to learn the tutorial of **openmeeg**, but I don't know how to build head.geom and head.cond, I didn't find this part of the tutorial in the openmeeg tutorial, so I want to ask you for some related tutorials or materials of this part.
Thanks!

**Comment by agramfort** [comment]
what do you mean? how to produce the BEM files i.e. the surfaces from the
T1 MRI?

**Comment by nana-zhang** [comment]
Hello, I see that building **geometric models, mesh and conductivity files** is mentioned in the openmeeg tutorial, but the tutorial did not mention how to build them, as shown in the following figure：
![image](https://user-images.githubusercontent.com/70929994/181255930-c2b4d4aa-8a2e-4d1c-b008-190ae4eeaf89.png)
![image](https://user-images.githubusercontent.com/70929994/181256016-56394c6c-44d1-41bc-af15-a82d62966240.png)
Sorry, I just started learning openmeeg, and the questions I may ask are stupid. If you can give me some advice, I will be very grateful！

**Comment by nana-zhang** [comment]
Maybe I should explain again. I mean how to get **.geom** files and  **.cond** files, whether these two files are generated **directly** or need to be **edited** by myself. If they can be generated directly, what are the related tutorials? If they need to be edited by myself, how are the related files such as **skull.tri**, **brain.tri**, **head.tri**  generated and how to obtain domains? If you can give me some suggestions, I will be very grateful!

**Comment by papadop** [comment]
You need to build these files by yourself with an editor. They are not generated by any tool yet. OpenMEEG is mostly a command line tool for which the inputs (except meshes) need to be entered by hand.

**Comment by papadop** [comment]
Maybe one day we will add some interface to help creating those files....
For now, I'm closing this issue (as strictly speaking this is not an issue).
Such questions are better directed to the mailing list (see https://openmeeg.github.io/contact.html) openmeeg-info@inria.fr
But in case of other problems do not hesitate to contact us on the above mailing list or in case of an issue through this forum.
Thank you.
