### ISSUE TITLE
Please explain the difference between the two .geom files for the same head.

### ISSUE THREAD

**Issue by vhs304305** [openmeeg/openmeeg#489]
The first geom file, head_model.geom, is the example file shipped with the openmeeg_sample_dataset.
////////////////////////////////////////////////
Domain Description 1.0

Interfaces 3 Mesh

skull.tri
brain.tri
head.tri

Domains 4

Domain Scalp 1 -3
Domain Brain -2 shared
Domain Air 3
Domain Skull 2 -1
////////////////////////////////////////////////

The second geom file is using all the same meshes, with different order list from the first file.
////////////////////////////////////////////////

Domain Description 1.0

Interfaces 3 Mesh

brain.tri
skull.tri
head.tri

Domains 4

Domain Brain -1
Domain Skull -2 1
Domain Scalp -3 2
Domain Air 3
////////////////////////////////////////////////

When using these two geom files in
om_assemble -HM head_model.geom head_model.cond tmp.hm,
the output, tmp.hm, are different.

Could anyone explain why?  I need to make sure the OpenMEEG is a reliable package.

**Comment by larsoner** [comment]
Closing as dup of #486
