### ISSUE TITLE
How to get Theodore Papadopoulo's attention to answer the questions and to fix the bugs?

### ISSUE THREAD

**Issue by vhs304305** [openmeeg/openmeeg#490]

**Comment by larsoner** [comment]
Closing as dup of #486

I would recommend reading all of this document, but specifically this section:

https://github.com/selfteaching/How-To-Ask-Questions-The-Smart-Way/blob/master/How-To-Ask-Questions-The-Smart-Way.md#if-you-cant-get-an-answer 

The TL;DR is that hopefully someone will be able to answer your question(s), but asking repeatedly is not generally a useful approach. Pinging with Theodore's GH handle -- which is already done in #486 -- should be enough. And maybe if after days or weeks or maybe a month there is no response, we can assume that he won't respond, and someone else will have to figure out how to fix these things.
