### ISSUE TITLE
BUG: Fix bugs with Python wrappers

### ISSUE THREAD

**Issue by larsoner** [openmeeg/openmeeg#508]
Several Python tests are marked with `@pytest.mark.xfail` and `@pytest.mark.skip` in `wrapping/python/openmeeg/tests/*.py`. These should be released and a new minor or patch version released.

- [x] `BAD_TYPE`: https://github.com/openmeeg/openmeeg/pull/529
- [x] `BAD_PYPY`: https://github.com/openmeeg/openmeeg/pull/533, fixed by @papadop in https://github.com/openmeeg/openmeeg/pull/536
- [x] `BAD_MKL`: https://github.com/openmeeg/openmeeg/pull/532
- [x] `BAD_MSVC`: https://github.com/openmeeg/openmeeg/pull/540

**Comment by papadop** [comment]
Is this related only to pypy and setuptools ? As far as I can tell, python tests are passing for me...
But I may missing something.
And indeed, it would be nice to remove those xfails.

**Comment by larsoner** [comment]
> Is this related only to pypy and setuptools ?

At least some are, yeah. I tried to use variable names and/or comments that made sense. But if you really want to try fixing one, just remove the `@pytest.mark.skipif` or `@pytest.mark.xfail` and the CIs will complain

**Comment by papadop** [comment]
Yes but for convenience, I'm looking at a way to reproduce the bug a my computer. That would be much easier.

**Comment by larsoner** [comment]
I think some can be reproduced by building python using setuptools rather than cmake. So build with -DENABLE_PYTHON=OFF and then separately use `OPENMEEG_USE_SWIG=1 python setup.py develop` (or install) in the wrapping/python directory.

I can try to write a little minimal script tomorrow probably...

**Comment by papadop** [comment]
That would be appreciated.....

**Comment by larsoner** [comment]
Locally on my macOS M1 machine I did (I also had a `-DCMAKE_PREFIX_PATH=/opt/OpenBLAS` but I doubt you need it):
```
rm -Rf build
PYTHON_OPT="-DENABLE_PYTHON=OFF" ./build_tools/cmake_configure.sh -DCMAKE_INSTALL_PREFIX=$PWD/install
cmake --build build --target install --config Release
export DYLD_LIBRARY_PATH=$PWD/install/lib
export OPENMEEG_LIB=$PWD/install/lib
export OPENMEEG_INCLUDE=$PWD/install/include/OpenMEEG
export OPENMEEG_DATA_PATH=$PWD/data
cd wrapping/python
OPENMEEG_USE_SWIG=1 python setup.py develop
pytest openmeeg/tests # passes
```
Even the `BAD_TYPE` tests passed, so I opened https://github.com/openmeeg/openmeeg/pull/529 to see if CIs agree we don't need that skip.

The other three are MSVC, MKL, and PYPY-related. MSVC you'd need a Windows build to debug properly. PyPy you'd need to use that for your Python interpreter. But MKL might be more doable with conda -- I already made a comment in the CI code about how to do this if you want to try (after installing `mkl` via conda):

https://github.com/openmeeg/openmeeg/blob/0c0d2b9a318aa3525d00331790a0fadcaf5435cf/.github/workflows/build_and_test.yml#L255-L258
