### ISSUE TITLE
VecLib cleanup

### ISSUE THREAD

**Issue by papadop** [openmeeg/openmeeg#521]
Are we use (or foresee to use) veclib on MacOs. Otherwise, there is some cleanup to be made (look at USE_VECLIB).

**Comment by larsoner** [comment]
+1 for removal. My vote is actually to allow only MKL, OpenBLAS, and maybe someday reference BLAS/LAPACK (Netlib?). I guess we could keep ATLAS if it's simple enough, but it's not tested on CIs so we have no guarantee it works. We'd want to add a job for it...

@agramfort okay with you to remove veclib on macOS?

**Comment by papadop** [comment]
ATLAS was our preferred choice a few years ago. Then a bug (some weird parallel stuff) made me switch to OpenBLAS.
It might be worth checking whether tests are now passing with ATLAS and compare performances...
I will remove the Veclib stuff if @agramfort is also OK.

**Comment by papadop** [comment]
Dibe with PR #525 (for the Veclib cleanup).
