### ISSUE TITLE
Copyright notice

### ISSUE THREAD

**Issue by papadop** [openmeeg/openmeeg#538]
I'm kind of pissed off with this long copyright notice. This is unmaintanable.
Instead I propose to put a short notice such as:

```
// Project Name : OpenMEEG
// © INRIA and ENPC under the French opensource license CeCILL-B.
// See full copyright notice in the file LICENSE.txt
// If you make a copy of this file, you must also provide the file LICENSE.txt.

```
The idea is to put the minimum important information in these lines and to refer
to the LICENSE.txt file for details. This is is much more maintainable this way.
We could also put more information such as a short list of contributions of each
contributor. This would have the benefit that we can easily acknowledge new
contributors such as @massich and @larsoner or even @yarikoptic  who did
a lot of work at the level of the build system with travis and now github actions.

Comments, suggestions, opinions ?

**Comment by agramfort** [comment]
sounds good to me

**Comment by larsoner** [comment]
Fine with me but double check the standard name, I think it's CECILL-B (capital E)

**Comment by larsoner** [comment]
SPDX short identifier at least from https://spdx.org/licenses/, but maybe we don't need to match that

**Comment by papadop** [comment]
Well the identifier is indeed CECILL-B but the full name is "CeCILL-B Free Software License Agreement".
I just copied what was there, but if we need to make corrections, let's do them !

**Comment by larsoner** [comment]
From my light searching the "e" seems to be lower case everywhere else so I'm happy with keeping it that way 👍

**Comment by larsoner** [comment]
This has been fixed
