### ISSUE TITLE
MAINT: Clean up stale branches

### ISSUE THREAD

**Issue by larsoner** [openmeeg/openmeeg#549]
@papadop I see four stale branches here (the `*release*` ones are fine):

https://github.com/openmeeg/openmeeg/branches/stale

Okay to delete them?

**Comment by larsoner** [comment]
Looks like some have been deleted now and what remains is just:

- [python_operators](https://github.com/openmeeg/openmeeg/tree/python_operators) for @papadop and
- [Calderon](https://github.com/openmeeg/openmeeg/tree/Calderon) for @agramfort 

@agramfort if you give me access to your fork I can just push it there (same for you @papadop if you want me to do it for `python_operators`, you can just add me at https://github.com/papadop/openmeeg/settings/access)

**Comment by agramfort** [comment]
ok I deleted Calderon and I pushed a copy in my fork

**Comment by papadop** [comment]
I made copies of those two too yesterday. I will delete the branches
