### ISSUE TITLE
DOC: Change documentation process

### ISSUE THREAD

**Issue by larsoner** [openmeeg/openmeeg#557]
User-readable changes are now tracked four places (not counting `git log`, which will always be there but isn't really user-readable):

1. In the GitHub Releases, e.g., [this one](https://github.com/openmeeg/openmeeg/releases/tag/2.4.7), which is automated with the click of a button and uses the PR titles
3. In [`ChangeLog`](https://github.com/openmeeg/openmeeg/blob/main/ChangeLog)
4. In [news on openmeeg.github.io](https://openmeeg.github.io/news.html)

I propose we:

1. Use the GitHub automatic PR-title-based "release notes"
2. Get rid of `ChangeLog`
3. Keep `news.html`, but refer people to the GitHub releases for a complete list of changes

And if anyone opens a PR to make a "big change" of some sort, we ask for a corresponding change in `news.html`. 

It's my first time thinking about this and I might have missed some stuff -- thoughts?

**Comment by papadop** [comment]
Definitely for getting rid of ChangeLog. It is an old method and this created continuous merge conflicts when used thoroughly. Anyway, we probably were not using well these last years.

For GitHub automatic PR-title-based "release notes", how does this work ? Do we need to format PRs in a specific way ? Do you have an example ? Most PRs are for things that we do not necessarily want to give details (e.g. all small bug corrections)... In the end, the news.html is probably the best way. We might want to structure it a little bit better in particular to keep the news of older releases somewhere....

Finally, is there a way to "share" the news.hml between the openmeeg repo and the web site repo ? Not a big deal if it's even a little bit complicated, but it would be nice to keep the news.hml file in sync with git revisions.

**Comment by larsoner** [comment]
> For GitHub automatic PR-title-based "release notes", how does this work ? Do we need to format PRs in a specific way ? 

By default it just links to all merged PRs using their titles. So the easiest way is to make sure each PR is opened with a title that makes sense as a changelog entry, or edit it to be reasonable before squash+merge. The slightly harder way (I think) is to tweak the release notes when making the release.

> Do you have an example ? Most PRs are for things that we do not necessarily want to give details (e.g. all small bug corrections)... In the end, the news.html is probably the best way. 

Yep I've done all releases this way, here are a couple of examples:

- https://github.com/openmeeg/openmeeg/releases/tag/2.5.5
- https://github.com/openmeeg/openmeeg/releases/tag/2.5.2

It's not perfect but for something almost automatic with no manual intervention needed, I think it's good enough.

> In the end, the news.html is probably the best way

Sure, this could be for big high-level stuff. Then the GitHub autogenerated notes could be for all the minor stuff. So `news.html` could highlight big changes and point to GitHub for a full changelog.

> Finally, is there a way to "share" the news.hml between the openmeeg repo and the web site repo ? Not a big deal if it's even a little bit complicated, but it would be nice to keep the news.hml file in sync with git revisions.

We could in principle have a CI job that pushes some stuff to news. But this would require building and maintaining the infrastructure, and I'm not sure exactly what we'd want to automate here anyway. It seems like it will probably take some manual curation/choosing of the things to highlight, in which case just editing the RST and pushing is probably quick enough anyway.
