### ISSUE TITLE
CI Win7 32bit VS2012 compile error (USE_OMP=ON)

### ISSUE THREAD

**Issue by dang-kai** [openmeeg/openmeeg#58]
The following 3 errors are given by the compiler wherever it meets "#pragma omp parallel for" in the file "operators.h":

operators.h(313): error C3015: initialization in OpenMP 'for' statement has improper form
          ....\src\assembleHeadMat.cpp(91) : see reference to function template instantiation 'void OpenMEEG::operatorSOpenMEEG::SymMatrix(const OpenMEEG::Mesh &,const OpenMEEG::Mesh &,T &,const double &,const unsigned int)' being compiled
          with
          [
              T=OpenMEEG::SymMatrix
          ]
operators.h(313): error C3017: termination test in OpenMP 'for' statement has improper form
operators.h(313): error C3019: increment in OpenMP 'for' statement has improper form

**Comment by agramfort** [comment]
@eolivi can I close ?

**Comment by eolivi** [comment]
yes : this has been implemented long ago
> #pragma omp parallel for
#ifndef OPENMP_3_0
for (int i=0; i< m.size();++i) {
Mesh::const_vertex_iterator vit = m.vertex_begin()+i;
#else
for (Mesh::const_vertex_iterator vit = m.vertex_begin(); vit < m.vertex_end(); ++vit) {
#endif
