### ISSUE TITLE
Where do I find libopenmp-dev?

### ISSUE THREAD

**Issue by ualsbombe** [openmeeg/openmeeg#599]
When building from source I get an error that libopenmp-dev cannot be localized. I am running a Linux Mint system 20.3. Do you know which repository I would have to add. I have not been able to find the lib using google

![billede](https://user-images.githubusercontent.com/17312936/204774579-9da2baf7-9859-4a9d-b176-4758e8392c98.png)

**Comment by agramfort** [comment]
if you have conda it should now be much easier to do

conda install openmeeg

**Comment by ualsbombe** [comment]
Thanks - managed to install via conda instead
