### ISSUE TITLE
Could you provide a binary for ARM Linux (`aarch64`) on PyPI?

### ISSUE THREAD

**Issue by hoechenberger** [openmeeg/openmeeg#663]
Hello, I'm just working on a Dev Container for MNE-Python on my M2 MacBook. I'm running a Debian 12 (Bookworm) Linux system of the `aarch64` architecture. Trying to `pip install "mne[full]"` currently fails as there's no `aarch64` wheel of OpenMEEG available. Would it be possible for you to provide one?

**Comment by larsoner** [comment]
In principle it should just require tweaking cibuildwheel a little bit. Feel free to kick it off with a PR if you want or I can try on Tuesday

**Comment by hoechenberger** [comment]
I don't have any experience with this, I'll leave it to you :)

But I realized there's more MNE deps missing on aarch64, most notably VTK

I will therefore try to stick with conga-forge for the time being (on which, I believe, I will have all or at least more deps satisfied than on PyPI)

But it would be great if in the long run, we could ensure that MNE-Python can be installed with `pip` on all supported platforms
