### ISSUE TITLE
Error at running OpenMEEG > `2.5.8` on Apple silicon

### ISSUE THREAD

**Issue by rcassani** [openmeeg/openmeeg#677]
Context: I'm updating code in [Brainstorm](https://github.com/brainstorm-tools/brainstorm3) to use newer versions of OpenMEEG

After tests in different OS, I realized that [releases on Github](https://github.com/openmeeg/openmeeg/releases) newer than `2.5.8` do not seem to run on Apple Silicon.

Test: Executing `om_assemble` get killed without showing the command options

Testing on:
* Chip: Apple M2
* macOS: Sonoma 14.5

---
* Releases (on GitHub) `2.5.6` to `2.5.8` work fine for Windows, Linux, macOS (Intel) and macOS (Apple silicon)
* Releases (on GitHub) up to the latest `2.5.11` work fine for Windows, Linux and macOS (Intel)

**Comment by larsoner** [comment]
What's a bit surprising is that these get tested in CIs every run, e.g., here:

https://github.com/openmeeg/openmeeg/actions/runs/9849204006/job/27192514140#step:7:6849

So it at least passes there. I also opened https://github.com/openmeeg/openmeeg/pull/678 specifically to check `om_assemble --help` and that runs as well. But locally I can reproduce the error!

I think I have a fix handy... I'll push it and a version bump to #678, test the artifact, and put a link here so you can test it, too. Assuming it works, I'll cut a release!

**Comment by larsoner** [comment]
Okay locally downloading and running this artifact from https://github.com/openmeeg/openmeeg/actions/runs/9879509083?pr=678 works for me:

https://github.com/openmeeg/openmeeg/actions/runs/9879509083/artifacts/1687901941

Can you give it a try and see if it works for you as well?

**Comment by rcassani** [comment]
Yes, it does work fine here

**Comment by larsoner** [comment]
Great, https://github.com/openmeeg/openmeeg/releases/tag/2.5.12 should also work then!
