### ISSUE TITLE
Unstable results

### ISSUE THREAD

**Issue by ftadel** [openmeeg/openmeeg#68]
Hello,

I'm observing frequently cases where the values are very high for one or two grid points, compared with the other values. An example with 14 electrodes (Emotiv Epoc headset) and the Colin27 template brain in Brainstorm.
Brainstorm protocol: https://www.dropbox.com/s/8qk83zpvwapjulf/bug2_protocol.zip?dl=0
OpenMEEG files: https://www.dropbox.com/s/80r0gsxetb752ts/bug2_openmeeg.zip?dl=0

Are there improvements to expect?
How do you suggest we handle these cases?

Thanks,
Francois

**Comment by agramfort** [comment]
@eolivi can you have a look at this before the release?
