### ISSUE TITLE
error #-1073741819

### ISSUE THREAD

**Issue by KLehongre** [openmeeg/openmeeg#70]
Hello,

I do not manage to compute my head model (EEG) using openMEEG.
I always get the error #-1073741819, regardless of the options used.
Here is the message in matlab: 

*\* Error: OpenMEEG call: om_minverser
*\*       "C:\Users\Katia LEHONGRE.brainstorm\tmp\openmeeg_hm.bin"
*\*       "D:\brainstorm_db\Alpha\anat\C_Subject07\tess_innerskull_bem_642V_openmeeg.bin"
*\* OpenMEEG error #-1073741819: 
*\* om_minverser version 2.2.0 (exported) compiled at Feb 19 2013 13:59:57
*\* 
*\* | ------ om_minverser
*\* | C:\Users\Katia LEHONGRE.brainstorm\tmp\openmeeg_hm.bin
*\* | D:\brainstorm_db\Alpha\anat\C_Subject07\tess_innerskull_bem_642V_openmeeg.bin
*\* | -----------------------
*\* 
*\* Many OpenMEEG crashes are due to a lack of memory.
*\* Reduce the number of vertices on each BEM layer and try again.

---

Thank you for your help,
best
katia

**Comment by eolivi** [comment]
Hello Katia,
What version are you using ? (OpenMEEG*.exe ?, git version... ?)
Have you tried the tests ?
How is the input matrix, you are trying to invert ?
Can you provide the result of this command please:
> om_matrix_info -i C:\Users\Katia LEHONGRE.brainstorm\tmp\openmeeg_hm.bin

(maybe your dataset is too large for BEM... do not go beyond 10000 vertices in total)

bye

**Comment by eolivi** [comment]
@Lehongre

**Comment by agramfort** [comment]
closing for non-responsiveness
