### ISSUE TITLE
A singularity in gain matrices generated using OpenMEEG

### ISSUE THREAD

**Issue by Ali-E-Haddad** [openmeeg/openmeeg#77]
Dear Sir/Ma'am

I use Brainstorm to generate head models and use the Gain matrices for further calculations.
I would like to report a singularity in the gain matrices generated using "Compute head model" with "Cortex surface," "EEG: OpenMEEG BEM," "Use adaptive integration," and the default "Colin27" anatomy and layer thicknesses.

The singularity is such that one column of the generated gain matrix is amplified by 10^3 or 10^4.
I have already reported this problem on the Brainstorm forum, but was told by the admin to report the problem to you.

Please consider fixing this issue,
Best regards.

**Comment by agramfort** [comment]
can you share the meshes of the bem model + the cortical surface you are
using? Ideally as .tri files used directly by openmeeg.

thanks for the issue report

**Comment by agramfort** [comment]
closing due to lack of response
