### ISSUE TITLE
ATLAS alternatives

### ISSUE THREAD

**Issue by maedoc** [openmeeg/openmeeg#82]
I'm working on a cluster with a bad ATLAS installation, is there any way to get CMake to link OpenMEEG to a self-built set of GotoBLAS2+LAPACK libraries, or does it really ahve to be ATLAS?

**Comment by agramfort** [comment]
never been tried AFAIK but can be nice to have.

I'd go with MKL for now ...

**Comment by papadop** [comment]
Yes. Recent version of atlas has a bug... For me, the symptom is:
The following tests FAILED:
	123 - DipGainInternalPot-HeadNNc1 (SEGFAULT)
	132 - InternalPot-dipoles-HeadNNc1 (OTHER_FAULT)
	152 - DipGainInternalPot-Head2 (SEGFAULT)
	161 - InternalPot-dipoles-Head2 (OTHER_FAULT)
	249 - cmp-EEGinternal-dip-Head2-dip1 (Failed)
	251 - cmp-EEGinternal-dip-Head2-dip2 (Failed)
	253 - cmp-EEGinternal-dip-Head2-dip3 (Failed)
	255 - cmp-EEGinternal-dip-Head2-dip4 (Failed)
	257 - cmp-EEGinternal-dip-Head2-dip5 (Failed)
which is very related to a specific dimension of matrices in this test. I have not (yet) being able to spot the exact problem in atlas, but replacing the DGEMM implementation (if I remember correctly) by a stock C one works perfectly.

**Comment by papadop** [comment]
Then, the code around blas/lapack implementation is really hairy. I just spend a couple of hours in trying to distangle it a bit and add OpenBlas support (which should be very close to GotoBlas), which I have access to. The good news is that it seems to works, no bugs and it is faster than atlas... I need to polish things out and to check many other configuration (MacOs, windows), but this seems promising. If you do not have acces to OpenBlas, it should not be too difficult to also add GotoBlas support (it should be mostly a little bit of cmake hacking plus a tweak in OpenMEEGMaths_Configure.h.

**Comment by papadop** [comment]
I'll keep you posted.

**Comment by maedoc** [comment]
I've no preference between OpenBLAS & GotoBLAS. If you push a branch with OpenBLAS support, I would test it.

**Comment by agramfort** [comment]
you should use openblas. gotoblas is not maintained anymore.

**Comment by papadop** [comment]
Do you need just OpenMEEG or the super-project ? If the former, I can push a branch (which will be a work-in progress). If you use the super-project, this is more complicated (as the OPenMEEG branch needs to be supported by a super-project branch). I intend to merge OpenMEEG proper and the super-project in one single repo, but that's a another story and I do not want to mix all of that at the same time...

**Comment by maedoc** [comment]
>  just OpenMEEG
is fine; I don't use the super project

**Comment by papadop** [comment]
@agramfort : Is veclib (apple) still sthg maintained and useful ? Do we need to keep this compatiblity in the code ? At some place there are 3 implementations of the same operation (VecLib, CLapack, raw lapack)...

**Comment by papadop** [comment]
OK. There is a branch on my clone named UniLapack. You can try it. Except if I broke sthg in the last minutes, it should work on linux for Lapack/OpenBlas/Atlas(with bugs)/ACML/MKL. But this is WIP. ow that I put my nose in this code, I want to simplify things and make them more modular. So more changes are coming.

**Comment by maedoc** [comment]
@papadop is there a way to tell CMake to use a custom built OpenBLAS and not system ATLAS?

**Comment by maedoc** [comment]
@papadop Sorry, my mistake: your branch _does_ pick up the custom built OpenBLAS, but OpenBLAS installs `include/lapacke.h` not `include/lapacke/lapacke.h` as expected by `OM_OpenBlas_Config.h`. Does this differ from your installation?

**Comment by maedoc** [comment]
I symlinked the header where it was expected, and it compiles, but only 8% of the tests pass. :/

**Comment by papadop** [comment]
My mistake.... I have several lapacke,h installed and I picked the wrong one. I'll correct that in a second. I'll recheck the test. Wait a second....

**Comment by papadop** [comment]
The OpenBlas detection should be better now... You probably can remove the workaround. To specify your OpenBlas implementation you can set the environment variable OpenBLAS_HOME (see FindOpenBlas.cmake). In my case, all test pass (I use the fedora OpenBlas packages).

**Comment by maedoc** [comment]
ok I recompiled but still have test failures, it must be how I compiled openblas.. anyway thanks for enabling this.

**Comment by agramfort** [comment]
@papadop please open a proper PR so I can see the diff and please avoid
removing things for mac.

thanks

**Comment by eolivi** [comment]
support for Openblas would be great !

**Comment by agramfort** [comment]
+1

do you volunteer? :)

**Comment by eolivi** [comment]
but @papadop  already started nope ?
I'll try ...

**Comment by agramfort** [comment]
@eolivi any idea why this happens?

https://travis-ci.org/openmeeg/openmeeg/jobs/132068916

see https://github.com/openmeeg/openmeeg/pull/112

**Comment by agramfort** [comment]
openblas is now supported

closing
