### ISSUE TITLE
Error when computing a head model using Brainstorm

### ISSUE THREAD

**Issue by FabienneCologne** [openmeeg/openmeeg#90]
Dear all,
I get the following error when computing a head model. Reducing the number of vertices did not solve the problem. Does anybody know this error and can help?
Best regards,
Fabienne
![fehleropenmeeg](https://cloud.githubusercontent.com/assets/18164301/14138611/6c48efbe-f66e-11e5-97e5-75975c6d2952.jpg)

**Comment by agramfort** [comment]
did you try with a very limited number of vertices? such as 500 per layer
for example.

**Comment by FabienneCologne** [comment]
Yes I’ve tried it with a limited number and it is not working. The PC that I am using has 64 GB working memory so I don’t think that this is the problem. Do you have other recommendations?




Von: Alexandre Gramfort [mailto:notifications@github.com]
Gesendet: Mittwoch, 30. März 2016 13:24
An: openmeeg/openmeeg
Cc: Fabienne Jung
Betreff: Re: [openmeeg/openmeeg] Error when computing a head model using Brainstorm (#90)

did you try with a very limited number of vertices? such as 500 per layer
for example.

**Comment by agramfort** [comment]
sorry then I don't know :(

**Comment by FabienneCologne** [comment]
Thank you for your help!

Von: Alexandre Gramfort [mailto:notifications@github.com]
Gesendet: Mittwoch, 30. März 2016 13:51
An: openmeeg/openmeeg
Cc: Fabienne Jung
Betreff: Re: [openmeeg/openmeeg] Error when computing a head model using Brainstorm (#90)

sorry then I don't know :(

**Comment by papadop** [comment]
Strange because this is just the inversion of the matrix. Can you post the openmeeg_hm.mat matrix ??

**Comment by FabienneCologne** [comment]
Unfortunately the matrix is to large to post it. What should I look for? Or can I send it to you somehow?

**Comment by agramfort** [comment]
use https://www.wetransfer.com/

**Comment by FabienneCologne** [comment]
fabienne.jung@uk-koeln.de
sent you some files

‘This is the matrix’

Download:

https://www.wetransfer.com/downloads/33e6b917a7f9771d81b026030f0b9d5c20160330153810/fcd078ed2ac60eaf4f96594dad49545420160330153810/25595d

Files (574 MB total)
openmeeg_hm.mat

Will be deleted on
6 April, 2016


Get more out of WeTransfer, get Plus
https://www.wetransfer.com/plus?trk=email-recipient_download


About WeTransfer: https://www.wetransfer.com/about
Contact: https://www.wetransfer.com/contact
Legal: https://www.wetransfer.com/legal

To make sure you can receive our emails, please add noreply@wetransfer.com to your [trusted contacts](http://we.tl/trustedcontacts)

**Comment by FabienneCologne** [comment]
fabienne.jung@uk-koeln.de
sent you some files

‘this is the matrix’

Download:

https://www.wetransfer.com/downloads/388e9cad3a6fe6141403fbb83bb5532620160330154605/77d0fe10350a1e19f3c476677f105e9e20160330154605/e7f186

Files (574 MB total)
openmeeg_hm.mat

Will be deleted on
6 April, 2016


Get more out of WeTransfer, get Plus
https://www.wetransfer.com/plus?trk=email-recipient_download


About WeTransfer: https://www.wetransfer.com/about
Contact: https://www.wetransfer.com/contact
Legal: https://www.wetransfer.com/legal

To make sure you can receive our emails, please add noreply@wetransfer.com to your [trusted contacts](http://we.tl/trustedcontacts)

**Comment by FabienneCologne** [comment]
Could anyone have a look at it? I have really no idea what the problem might be...

**Comment by agramfort** [comment]
can you try to run:

om_minverser.exe openmeeg_hm.mat openmeeg_hminv.mat

from the command line?

**Comment by FabienneCologne** [comment]
Could you please explain this a little bit more? Because…

>> om_minverser.exe
Undefined variable "om_minverser" or class "om_minverser.exe".

Von: Alexandre Gramfort [mailto:notifications@github.com]
Gesendet: Donnerstag, 31. März 2016 15:12
An: openmeeg/openmeeg
Cc: Fabienne Jung
Betreff: Re: [openmeeg/openmeeg] Error when computing a head model using Brainstorm (#90)

can you try to run:

om_minverser.exe openmeeg_hm.mat openmeeg_hminv.mat

from the command line?

**Comment by papadop** [comment]
Well... You need to find the command om_inverser. It should be installed somewhere in your brainstorm directory as far as I remember.

**Comment by papadop** [comment]
Just for the record:
om_matrix_info -sym -i openmeeg_hm.mat
om_matrix_info version 2.3.dev (Unversioned directory) compiled at Jan 27 2016 15:08:39

Loading : openmeeg_hm.mat
Dimensions : 13446 x 13446
Min Value : -0.00732181 (13297,13297)
Max Value : 0.00175977 (6801,12433)
First Values
-0.00223721 0.000101948 0.000108822 8.4117e-06 1.54928e-05 
-0.00275752 9.27579e-05 0.0001301 0.000132601 
-0.00274182 1.26972e-05 0.000140187 
-0.0029428 0.000102855 
-0.00291305 

And it requires about 1.4Gb just to load. I'm currently inverting it on a 16Gb machine, it seems to work up to now.

**Comment by papadop** [comment]
Actually I may have a clue... The inversion (not yet finished) is still running and requires 1.7Gb of memory. I seem to remember that 32bits processes on windows are limited to 2Gb of memory which is very close to 1.7Gb. I wonder whether you no hit by this limitation. If so and if your operating system is windows 64 bit, make sure you use the 64 bits versions of OpenMEEG. Normally brainstorm knows how to download it. Normally, if you find the om_minverser executable, then the directory name where it is located should refer to the version brainstorm downloaded for you.... 
If you are on a 32 bits system, and you hit this memory limit. There is very little we can do as this is a hard limitation of windows (there might be tricks, but I'm not a specialist).

**Comment by papadop** [comment]
And for the record, the inversion just succeeded here using no more than 1.7Gb (it took a few minutes).

**Comment by FabienneCologne** [comment]
Ok. Thank you very much! We have a 64 bit system with 64 GB working memory so this is not the problem, I think.

When I start om_inverse.exe I get the following message.

The program cannot be started. Because a .dll file is missing.

Von: Theodore Papadopoulo [mailto:notifications@github.com]
Gesendet: Donnerstag, 31. März 2016 16:54
An: openmeeg/openmeeg
Cc: Fabienne Jung
Betreff: Re: [openmeeg/openmeeg] Error when computing a head model using Brainstorm (#90)


And for the record, the inversion just succeeded here using no more than 1.7Gb (it took a few minutes).

**Comment by FabienneCologne** [comment]
I have installed it again and get the same error message… :(

Von: Theodore Papadopoulo [mailto:notifications@github.com]
Gesendet: Donnerstag, 31. März 2016 16:54
An: openmeeg/openmeeg
Cc: Fabienne Jung
Betreff: Re: [openmeeg/openmeeg] Error when computing a head model using Brainstorm (#90)


And for the record, the inversion just succeeded here using no more than 1.7Gb (it took a few minutes).

**Comment by papadop** [comment]
OK.... This is somewhat strange as your image from the start of the post seems to indicate that om_minverser had run (since it outputed some message). Are you sure, it is the same executable that is used ?
 Also, in which directory did you find this executable (just to be sure that brainstorm installed the 64 bits version of OpenMEEG). But indeed, the operating system is not guilty....

**Comment by FabienneCologne** [comment]
This is the path of the version I’ve just installed. The error message does also lead to this path…




Von: Theodore Papadopoulo [mailto:notifications@github.com]
Gesendet: Donnerstag, 31. März 2016 17:21
An: openmeeg/openmeeg
Cc: Fabienne Jung
Betreff: Re: [openmeeg/openmeeg] Error when computing a head model using Brainstorm (#90)


OK.... This is somewhat strange as your image from the start of the post seems to indicate that om_minverser had run (since it outputed some message). Are you sure, it is the same executable that is used ?
Also, in which directory did you find this executable (just to be sure that brainstorm installed the 64 bits version of OpenMEEG). But indeed, the operating system is not guilty....

**Comment by agramfort** [comment]
can you try to install

Visual C++ 2010 Redistributable package (google and download for free on
microsoft.com).

?

cf
http://neuroimage.usc.edu/forums/archive/index.php/t-1138.html?s=8f45f39bc0ff2aa42fd284400c8f7184

**Comment by FabienneCologne** [comment]
I’m going to try that!

Von: Alexandre Gramfort [mailto:notifications@github.com]
Gesendet: Freitag, 1. April 2016 09:50
An: openmeeg/openmeeg
Cc: Fabienne Jung
Betreff: Re: [openmeeg/openmeeg] Error when computing a head model using Brainstorm (#90)

can you try to install

Visual C++ 2010 Redistributable package (google and download for free on
microsoft.com).

?

cf
http://neuroimage.usc.edu/forums/archive/index.php/t-1138.html?s=8f45f39bc0ff2aa42fd284400c8f7184

**Comment by FabienneCologne** [comment]
Same error… :(



Von: Alexandre Gramfort [mailto:notifications@github.com]
Gesendet: Freitag, 1. April 2016 09:50
An: openmeeg/openmeeg
Cc: Fabienne Jung
Betreff: Re: [openmeeg/openmeeg] Error when computing a head model using Brainstorm (#90)

can you try to install

Visual C++ 2010 Redistributable package (google and download for free on
microsoft.com).

?

cf
http://neuroimage.usc.edu/forums/archive/index.php/t-1138.html?s=8f45f39bc0ff2aa42fd284400c8f7184

**Comment by agramfort** [comment]
then I am clueless...

**Comment by FabienneCologne** [comment]
When executing


om_minverser.exe openmeeg_hm.mat openmeeg_hminv.mat


via command line this happens…




Von: Alexandre Gramfort [mailto:notifications@github.com]
Gesendet: Freitag, 1. April 2016 10:15
An: openmeeg/openmeeg
Cc: Fabienne Jung
Betreff: Re: [openmeeg/openmeeg] Error when computing a head model using Brainstorm (#90)

then I am clueless...

**Comment by FabienneCologne** [comment]
… we also used different Matlab versions and have really no further idea.

Would there be the possibility to send the teamviewer ID and password of our PC so that you could have a look? Maybe we are doing something obvious wrong that we’re overseeing…

Best regards,
Fabienne


Von: Alexandre Gramfort [mailto:notifications@github.com]
Gesendet: Freitag, 1. April 2016 10:15
An: openmeeg/openmeeg
Cc: Fabienne Jung
Betreff: Re: [openmeeg/openmeeg] Error when computing a head model using Brainstorm (#90)

then I am clueless...

**Comment by FabienneCologne** [comment]
Dear all,
we uninstalled all compilers and frameworks and reinstalled them (explicitly adviced versions)
![bild1](https://cloud.githubusercontent.com/assets/18164301/14345586/0b174cd6-fcae-11e5-8631-8b0e4875caa2.jpg)
. Nothing changed. Same error.

Furthermore, we followed the instructions posted for the same error in this forum and replaced the binary files in the openmeeg folder.

om_minverser.exe crash
#76 opened on 16 Sep 2015 by MartinFRE

We receive a different error then (attached)

Does anybody have further advice?

**Comment by agramfort** [comment]
brainstorm install is now finally fixed.
