### ISSUE TITLE
Error computing Head model with brainstorm

### ISSUE THREAD

**Issue by Steve32** [openmeeg/openmeeg#91]
I´m analyzing a multi-subject EEG study. I calculated the first head model without any error but on the following subjects I get the attached error message. Reducing vertices didn't solve the problem. Could you please help me to solve this issue?

![bildschirmfoto 2016-03-30 um 14 15 42](https://cloud.githubusercontent.com/assets/18166904/14141839/f6ea3106-f681-11e5-9763-1d0138f543ac.png)

Thanks,

Steve

**Comment by agramfort** [comment]
how did you generate the meshes? did you eye ball them? are they
intersecting?

**Comment by Steve32** [comment]
On visual inspection they aren't intersecting. I created them using the brainstorm function Generate BEM from imported freesurfer T1 images.

**Comment by agramfort** [comment]
please share the files if you are sure that they don't touch or intersects.
This would suggest a bug.

**Comment by Steve32** [comment]
Thank you so much! I zipped the subject file with the anat and data file from brainstorm: 
https://onedrive.live.com/redir?resid=DF232FF6BFCF2A08!36838&authkey=!AHWthEP6ThKweRY&ithint=file%2czip

**Comment by agramfort** [comment]
indeed your files are valid. I converted them to .tri for openmeeg with a
valid .geom file:

https://dl.dropboxusercontent.com/u/2140486/Archive.zip

and:

om_check_geom -g test.geom

says that everything is OK. So I suppose you use an older version of
openmeeg and that the bug
has now been fixed.
