### ISSUE TITLE
Command line outputs say Conductivity = 0 for all domains

### ISSUE THREAD

**Issue by laurajanem** [openmeeg/openmeeg#94]
Hello,

I've been using om_assemble to create a head matrix using the .geom, .cond, and .tri files attached. The program completes with no errors, and generates the head matrix as expected.  However, as it is running, the console outputs say 'Conductivity : 0' for all domains, even though they are non-zero in the .cond file.  Here is a screenshot of the outputs:

![programoutput_conductivity0](https://cloud.githubusercontent.com/assets/17499453/14471894/ae534d46-00be-11e6-832e-13b581f7c71e.png)

Is this just an error in what is being written to the command line, or is the .cond file not being interpreted correctly (or is it in the wrong format)? I'm not sure how to test this.

Files:
https://www.dropbox.com/sh/yiw9ty8u92ingyf/AADg65oMf6gr3FPsT7zkIy2Qa?dl=0

Computer stats: Windows 7 Professional, Intel Xeon CPU E5-2630 vs @2.40 GHz (2 processors) 64.0 GB RAM

I am using the Windows binaries provided by @dang-kai in a previous thread:  #76.

Thanks!

**Comment by dang-kai** [comment]
Hi, 

I've managed to reproduce your problem on my machine.
The problem can be solved by simply changing the version number in the .geom file from 1.0 to 1.1, as suggested by the warning information in the output you have posted :)  More information about the .geom file can be found here: http://openmeeg.gforge.inria.fr/download/tutorial-3.0.pdf

Here is the correct output for you to compare:
```
| ------ om_assemble.exe
| -HM
| openmeeg.geom
| openmeeg.cond
| hm.mat
| -----------------------
This geometry is a NESTED geometry.
Info:: Mesh name/ID : 1
                # vertices  : 7682
                # triangles : 15360
                Euler characteristic : 2
                Min Area : 2.09654e-06
                Max Area : 1.30694e-05
Info:: Mesh name/ID : 2
                # vertices  : 5762
                # triangles : 11520
                Euler characteristic : 2
                Min Area : 2.93562e-06
                Max Area : 1.64497e-05
Info:: Mesh name/ID : 3
                # vertices  : 2562
                # triangles : 5120
                Euler characteristic : 2
                Min Area : 1.18474e-05
                Max Area : 5.1181e-05
Info:: Domain name : Scalp
                Conductivity : 1
                Composed by interfaces : +2 -3
                Interface "2"= { mesh "2" }
                Interface "3"= { mesh "3"(outermost) }
Info:: Domain name : Brain
                Conductivity : 1
                Composed by interfaces : -1
                Interface "1"= { mesh "1" }
Info:: Domain name : Air
                Conductivity : 0
                Composed by interfaces : +3
                Considered as the outermost domain.
                Interface "3"= { mesh "3"(outermost) }
Info:: Domain name : Skull
                Conductivity : 0.0125
                Composed by interfaces : +1 -2
                Interface "1"= { mesh "1" }
                Interface "2"= { mesh "2" }
```

@mclerc @papadop @agramfort Is there still necessity to support the old version geom file?

**Comment by agramfort** [comment]
the old format is what 99% of our users use (via brainstorm and fieldtrip)

they run openmeeg from a GUI so they don't see all log messages.

at least is should not break or worth pass with a silent bug.

@dang-kai @papadop let's try to make this release happen so we can
ship new tested binaries for our users ASAP.

**Comment by agramfort** [comment]
running `om_geometry_info -g openmeeg.geom` on these files should crash with a meaningful error message.

[openmeeg_geom_cond_tri_files 2.zip](https://github.com/openmeeg/openmeeg/files/1061051/openmeeg_geom_cond_tri_files.2.zip)

@eolivi can you have a look?

**Comment by eolivi** [comment]
Yes, I had a look:
The thing is the geom file you gave me, is an hybrid version: i.e it is neither a 1.0 nor a 1.1 version, it is in between and should not exist (this geomfile is written as an 1.1 version but its header says 1.0), that is why the bug.

when running a pure 1.0 version, one has correctly the conductivities:
> | ------ om_assemble
| -hm
| /user/eolivi/home/src/om2.2/openmeeg-release-2.2/data/Models/Head2/Head2.geom
| openmeeg.cond
| a.mat
| -----------------------
(DEPRECATED) Please consider updating your geometry file to the new format 1.1 (see data/README.rst): /user/eolivi/home/src/om2.2/openmeeg-release-2.2/data/Models/Head2/Head2.geom
(DEPRECATED) Keyword shared is useless. Please consider updating your geometry file to the new format 1.1 (see data/README.rst): /user/eolivi/home/src/om2.2/openmeeg-release-2.2/data/Models/Head2/Head2.geom
This geometry is a NESTED geometry.
Info:: Mesh name/ID : 1
		# vertices  : 162
		# triangles : 320
		Euler characteristic : 2
		Min Area : 0.0304976
		Max Area : 0.0386928
Info:: Mesh name/ID : 2
		# vertices  : 162
		# triangles : 320
		Euler characteristic : 2
		Min Area : 0.0272728
		Max Area : 0.0346012
Info:: Mesh name/ID : 3
		# vertices  : 162
		# triangles : 320
		Euler characteristic : 2
		Min Area : 0.0360322
		Max Area : 0.0457145
Info:: Domain name : Scalp
		**Conductivity : 1**
		Composed by interfaces : +1 -3 
		Interface "1"= { mesh "1" }
		Interface "3"= { mesh "3"(outermost) }
...

**Comment by eolivi** [comment]
I would close this, as it is very rare to find an hybrid geom file.
ok ?

**Comment by agramfort** [comment]
it should crash with a bad formatting error message

**Comment by eolivi** [comment]
https://github.com/openmeeg/openmeeg/pull/218
